### ISSUE TITLE
[bug] Cannot startup clean docker image -- "Cannot read property 'logEnabled' of undefined

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#115]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: 1.2.3

**Describe the bug**
Upon a first-time install of the current docker image the docker image cannot start (either with docker-compose or just docker). It exits with the following error:

 ______                       _     ___                  _   _   
|___  /                      (_)   |__ \                | | | |  
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ 
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ 
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |        
                           |__/                       |_|        

2020-12-28 21:04:46.146 WARN STORE: settings.json not found
2020-12-28 21:04:46.212 WARN STORE: scenes.json not found
2020-12-28 21:04:46.213 WARN STORE: nodes.json not found
/bin/sh: git: not found
2020-12-28 21:04:47.835 INFO APP: Version: 1.0.0-alpha.1
2020-12-28 21:04:47.836 INFO APP: Application path:/usr/src/app
TypeError: Cannot read property 'logEnabled' of undefined
    at setupLogging (/usr/src/app/app.js:43:31)
    at startGateway (/usr/src/app/app.js:56:3)
    at start (/usr/src/app/app.js:38:3)
    at /usr/src/app/bin/www:98:5
    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/src/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

**To Reproduce**
1. Pull docker image
2. Start the image using "docker run --rm -it -p 8091:8091 --device=/dev/ttyACM0 --mount source=zwavejs2mqtt,target=/usr/src/app/store zwavejs/zwavejs2mqtt:latest"
3. Error

**Expected behavior**
The docker image should start...

**Additional context**
Docker version: 20.10.1, build 831ebea
OS: Raspbian, 32 bit (armv7l)

**Comment by robertsLando** [comment]
@blhoward2 have you used dev tag?

**Comment by blhoward2** [comment]
No, I pulled the latest image and ran the docker command straight from the readme.

**Comment by blhoward2** [comment]
Cloning and building a custom docker image starts fine. Bad build?

**Comment by robertsLando** [comment]
So you used latest tag, try to pull `dev` tag. I think that was a problem we have fixed some weeks ago

**Comment by t00** [comment]
I had the same problem and using a dev tag instead of latest works. Alternative would be probably to create a dummy settings.json file:

{"mqtt":{},"gateway":{},"zwave":{}}

By the way - is it possible to disable storing d8d2dd23.values.jsonl on disk? Constant disk writes add wear to storage for embedded devices...

**Comment by robertsLando** [comment]
node values are not stored on disk, there is a store handled by zwave-js, I dunno if writes can be reduced, need to ask to @AlCalzone that is the author of zwavejs

**Comment by robertsLando** [comment]
@t00 I have created https://github.com/zwave-js/node-zwave-js/issues/1255 So I can close this one
