### ISSUE TITLE
[bug] Yale Conexis L1 dead on 4.4.0

### ISSUE THREAD

**Issue by lolouk44** [zwave-js/zwavejs2mqtt#1273]
### Version

**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: <version here, you can find it on control panel>
zwave-js version: <version here, you can find it on control panel>

### Describe the bug

Although an HA user, issue doesn't appear to be HA related.
My container got updated to :latest tag today, since my Yale Conexis ends up dead.
I can bring it back to Alive by manually unlocking it, but when I manually lock it back up it ends up dead again
Reverted to 4.3.1 and it works again...

### To Reproduce

1. Manually unlock Conexis
2. Manually lock Conexis

### Expected behavior

lock does not become dead

### Additional context

I have tried to heal the network and tried to update the lock's data to no avail.
I've also tried to restart the server/container.
Here are some logs if that helps:
```
2021-05-25 18:12:41.117 INFO APP: GET /api/settings 304 64.731 ms - -
2021-05-25 18:12:41.129 INFO APP: GET /api/auth-enabled 304 2.097 ms - -
2021-05-25 18:12:56.212 INFO ZWAVE: Calling api isFailedNode with args: [ 1, [length]: 1 ]
2021-05-25 18:12:56.224 INFO ZWAVE: Calling api isFailedNode with args: [ 5, [length]: 1 ]
2021-05-25 18:12:56.239 INFO ZWAVE: Success zwave api call isFailedNode { success: true, message: 'Success zwave api call', result: false }
2021-05-25 18:12:56.250 INFO ZWAVE: Success zwave api call isFailedNode { success: true, message: 'Success zwave api call', result: true }
2021-05-25 18:13:20.520 INFO ZWAVE: Calling api beginHealingNetwork with args: [ [length]: 0 ]
2021-05-25 18:13:20.532 INFO ZWAVE: Controller status: Healing process IN PROGRESS. Healed 1 nodes
2021-05-25 18:13:20.535 INFO ZWAVE: Success zwave api call beginHealingNetwork { success: true, message: 'Success zwave api call', result: true }
2021-05-25 18:13:20.543 INFO ZWAVE: Controller status: Healing process COMPLETED. Healed 1 nodes
2021-05-25 18:13:29.442 INFO ZWAVE: Calling api isFailedNode with args: [ 1, [length]: 1 ]
2021-05-25 18:13:29.453 INFO ZWAVE: Calling api isFailedNode with args: [ 5, [length]: 1 ]
2021-05-25 18:13:29.467 INFO ZWAVE: Success zwave api call isFailedNode { success: true, message: 'Success zwave api call', result: false }
2021-05-25 18:13:29.476 INFO ZWAVE: Success zwave api call isFailedNode { success: true, message: 'Success zwave api call', result: true }
2021-05-25 18:13:54.991 INFO ZWAVE: Calling api isFailedNode with args: [ 5, [length]: 1 ]
2021-05-25 18:13:55.010 INFO ZWAVE: Success zwave api call isFailedNode { success: true, message: 'Success zwave api call', result: true }
2021-05-25 18:14:02.297 INFO ZWAVE: Calling api refreshValues with args: [ 5, [length]: 1 ]
2021-05-25 18:14:09.430 INFO ZWAVE: Success zwave api call refreshValues { success: true, message: 'Success zwave api call', result: undefined }
2021-05-25 18:17:28.099 INFO ZWAVE: Node 5: has returned from the dead
2021-05-25 18:17:28.186 INFO ZWAVE: Node 5: value added 5-98-0-currentMode => 255
2021-05-25 18:17:28.189 INFO ZWAVE: Node 5: value added 5-98-0-targetMode => 0
2021-05-25 18:17:28.191 INFO ZWAVE: Node 5: value added 5-98-0-outsideHandlesCanOpenDoor => false,false,false,false
2021-05-25 18:17:28.191 INFO ZWAVE: Node 5: value added 5-98-0-insideHandlesCanOpenDoor => false,false,false,false
2021-05-25 18:17:28.192 INFO ZWAVE: Node 5: value added 5-98-0-latchStatus => open
2021-05-25 18:17:28.192 INFO ZWAVE: Node 5: value added 5-98-0-boltStatus => locked
2021-05-25 18:17:28.193 INFO ZWAVE: Node 5: value added 5-98-0-doorStatus => closed
2021-05-25 18:17:28.194 INFO ZWAVE: Node 5: value added 5-98-0-lockTimeout => 0
2021-05-25 18:17:28.194 INFO ZWAVE: Node 5: value added 5-98-0-operationType => 1
2021-05-25 18:17:28.195 INFO ZWAVE: Node 5: value added 5-98-0-outsideHandlesCanOpenDoorConfiguration => false,false,false,false
2021-05-25 18:17:28.195 INFO ZWAVE: Node 5: value added 5-98-0-insideHandlesCanOpenDoorConfiguration => false,false,false,false
2021-05-25 18:17:28.196 INFO ZWAVE: Node 5: value added 5-98-0-lockTimeoutConfiguration => undefined
2021-05-25 18:17:28.196 INFO ZWAVE: Node 5: value added 5-112-0-1 => 3
2021-05-25 18:17:28.197 INFO ZWAVE: Node 5: value added 5-112-0-2 => 255
2021-05-25 18:17:28.197 INFO ZWAVE: Node 5: value added 5-112-0-3 => 30
2021-05-25 18:17:28.198 INFO ZWAVE: Node 5: value added 5-112-0-4 => 5
2021-05-25 18:17:28.198 INFO ZWAVE: Node 5: value added 5-112-0-7 => 180
2021-05-25 18:17:28.199 INFO ZWAVE: Node 5: value added 5-113-0-alarmType => 144
2021-05-25 18:17:28.199 INFO ZWAVE: Node 5: value added 5-113-0-alarmLevel => 3
2021-05-25 18:17:28.200 INFO ZWAVE: Node 5: value added 5-113-0-Access Control-Lock state => 11
2021-05-25 18:17:28.200 INFO ZWAVE: Node 5: value added 5-114-0-manufacturerId => 297
2021-05-25 18:17:28.201 INFO ZWAVE: Node 5: value added 5-114-0-productType => 26112
2021-05-25 18:17:28.201 INFO ZWAVE: Node 5: value added 5-114-0-productId => 2
2021-05-25 18:17:28.202 INFO ZWAVE: Node 5: value added 5-128-0-level => 100
2021-05-25 18:17:28.202 INFO ZWAVE: Node 5: value added 5-128-0-isLow => false
2021-05-25 18:17:28.202 INFO ZWAVE: Node 5: value added 5-134-0-libraryType => 3
2021-05-25 18:17:28.203 INFO ZWAVE: Node 5: value added 5-134-0-protocolVersion => 4.61
2021-05-25 18:17:28.203 INFO ZWAVE: Node 5: value added 5-134-0-firmwareVersions => 33.16
2021-05-25 18:17:28.203 INFO ZWAVE: Node 5: value added 5-134-0-hardwareVersion => undefined
2021-05-25 18:17:28.204 INFO ZWAVE: Node 5: value added 5-139-0-dateAndTime => undefined
2021-05-25 18:17:28.212 INFO ZWAVE: Node 5 ready: Yale - SD-L1000-CH (Conexis L1)
2021-05-25 18:17:28.241 INFO ZWAVE: Node 5: value updated: 98-0-currentMode 255 => 255
2021-05-25 18:17:28.243 INFO ZWAVE: Node 5: value updated: 98-0-outsideHandlesCanOpenDoor false,false,false,false => false,false,false,false
2021-05-25 18:17:28.245 INFO ZWAVE: Node 5: value updated: 98-0-insideHandlesCanOpenDoor false,false,false,false => false,false,false,false
2021-05-25 18:17:28.246 INFO ZWAVE: Node 5: value updated: 98-0-latchStatus open => open
2021-05-25 18:17:28.248 INFO ZWAVE: Node 5: value updated: 98-0-boltStatus locked => locked
2021-05-25 18:17:28.249 INFO ZWAVE: Node 5: value updated: 98-0-doorStatus closed => closed
2021-05-25 18:17:28.250 INFO ZWAVE: Node 5: value updated: 98-0-lockTimeout 0 => 0
2021-05-25 18:18:09.887 INFO ZWAVE: Node 5 is now dead
2021-05-25 18:18:18.074 ERROR ZWAVE-SERVER: Z-Wave error Failed to send the command after 3 attempts (Status NoAck)
ZWaveError: Failed to send the command after 3 attempts (Status NoAck)
at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:2316:23)
at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:2439:28)
at DoorLockCCAPI.set (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/DoorLockCC.ts:292:21)
at Proxy.DoorLockCCAPI.<computed> (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/DoorLockCC.ts:140:15)
at ZWaveNode.setValue (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:756:14)
at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:19:44)
at Object.node (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:37:91)
at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:91:99)
at WebSocket.<anonymous> (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:44:45)
at WebSocket.emit (node:events:378:20)
2021-05-25 18:18:20.956 INFO ZWAVE: Calling api refreshValues with args: [ 5, [length]: 1 ]
2021-05-25 18:18:25.712 INFO ZWAVE: Node 5: has returned from the dead
2021-05-25 18:18:45.071 INFO ZWAVE: Success zwave api call refreshValues { success: true, message: 'Success zwave api call', result: undefined }
2021-05-25 18:18:56.774 INFO ZWAVE: Node 5 is now dead
2021-05-25 18:19:04.821 ERROR ZWAVE-SERVER: Z-Wave error Failed to send the command after 3 attempts (Status NoAck)
ZWaveError: Failed to send the command after 3 attempts (Status NoAck)
at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:2316:23)
at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:2439:28)
at DoorLockCCAPI.set (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/DoorLockCC.ts:292:21)
at Proxy.DoorLockCCAPI.<computed> (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/DoorLockCC.ts:140:15)
at ZWaveNode.setValue (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:756:14)
at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:19:44)
at Object.node (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:37:91)
at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:91:99)
at WebSocket.<anonymous> (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:44:45)
at WebSocket.emit (node:events:378:20)
2021-05-25 18:19:08.397 ERROR ZWAVE-SERVER: Z-Wave error The message cannot be sent because node 5 is dead
ZWaveError: The message cannot be sent because node 5 is dead
at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:2252:12)
at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:2439:17)
at DoorLockCCAPI.set (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/DoorLockCC.ts:292:3)
at Proxy.DoorLockCCAPI.<computed> (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/DoorLockCC.ts:140:4)
at ZWaveNode.setValue (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:756:4)
at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:19:33)
at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:91:62)
2021-05-25 18:19:20.162 ERROR ZWAVE-SERVER: Z-Wave error The message cannot be sent because node 5 is dead
ZWaveError: The message cannot be sent because node 5 is dead
at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:2252:12)
at Driver.sendCommand (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:2439:17)
at DoorLockCCAPI.set (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/DoorLockCC.ts:292:3)
at Proxy.DoorLockCCAPI.<computed> (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/DoorLockCC.ts:140:4)
at ZWaveNode.setValue (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:756:4)
at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:19:33)
at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:91:62)
2021-05-25 18:19:31.778 WARN APP: Shutdown detected: closing clients...
2021-05-25 18:19:31.780 INFO GATEWAY: Closing Gateway...
2021-05-25 18:19:31.793 INFO ZWAVE-SERVER: Server closed
2021-05-25 18:19:31.797 INFO ZWAVE-SERVER: Client disconnected
2021-05-25 18:19:31.815 INFO ZWAVE: Client closed
2021-05-25 18:19:39.135 INFO ZWAVE: Next update scheduled for: Wed May 26 2021 00:00:00 GMT+0000 (Coordinated Universal Time)
2021-05-25 18:19:42.298 INFO ZWAVE: Zwave driver is ready
2021-05-25 18:19:42.299 INFO ZWAVE: Controller status: Driver ready
2021-05-25 18:19:42.311 INFO ZWAVE: Scanning network with homeid: 0xde677210
2021-05-25 18:19:42.313 INFO ZWAVE: Node 1 is alive
2021-05-25 18:19:42.362 INFO ZWAVE-SERVER: ZwaveJS server listening on port 3000
2021-05-25 18:19:42.379 INFO ZWAVE: Node 1 ready: AEON Labs - ZW090 (Z‐Stick Gen5 USB Controller)
2021-05-25 18:19:45.883 INFO ZWAVE: Node 5 is dead
2021-05-25 18:19:45.885 INFO ZWAVE: Controller status: Scan completed
2021-05-25 18:19:45.885 INFO ZWAVE: Network scan complete. Found: 2 nodes
2021-05-25 18:19:52.778 INFO APP: GET /control-panel 304 16.368 ms - -
2021-05-25 18:19:52.830 INFO APP: GET /static/css/app.ef6670977eb0e203b441.css 304 7.464 ms - -
2021-05-25 18:19:52.833 INFO APP: GET /static/js/app.98cf5561823b88c93aa4.js 304 5.638 ms - -
2021-05-25 18:19:53.056 INFO APP: GET /api/auth-enabled 304 10.352 ms - -
2021-05-25 18:19:53.115 INFO APP: GET /static/logo.png 304 1.393 ms - -
2021-05-25 18:19:53.221 INFO APP: GET /static/fonts/MaterialIcons-Regular.fa3334f.woff2 304 1.701 ms - -
2021-05-25 18:19:53.319 INFO APP: GET /api/settings 304 93.429 ms - -
2021-05-25 18:19:53.328 INFO APP: GET /static/favicons/favicon-32x32.png 304 0.987 ms - -
2021-05-25 18:19:53.335 INFO APP: GET /api/auth-enabled 304 1.749 ms - -
2021-05-25 18:22:56.591 WARN APP: Shutdown detected: closing clients...
2021-05-25 18:22:56.593 INFO GATEWAY: Closing Gateway...
2021-05-25 18:22:56.605 INFO ZWAVE-SERVER: Server closed
2021-05-25 18:22:56.607 INFO ZWAVE-SERVER: Client disconnected
2021-05-25 18:22:56.627 INFO ZWAVE: Client closed
2021-05-25 18:23:19.962 INFO ZWAVE: Next update scheduled for: Wed May 26 2021 00:00:00 GMT+0000 (Coordinated Universal Time)
2021-05-25 18:23:30.815 INFO ZWAVE: Zwave driver is ready
2021-05-25 18:23:30.816 INFO ZWAVE: Controller status: Driver ready
2021-05-25 18:23:30.825 INFO ZWAVE: Scanning network with homeid: 0xde677210
2021-05-25 18:23:30.828 INFO ZWAVE: Node 1 is alive
2021-05-25 18:23:30.881 INFO ZWAVE-SERVER: ZwaveJS server listening on port 3000
2021-05-25 18:23:30.903 INFO ZWAVE: Node 1 ready: AEON Labs - ZW090 (Z‐Stick Gen5 USB Controller)
2021-05-25 18:23:34.420 INFO ZWAVE: Node 5 is dead
2021-05-25 18:23:34.421 INFO ZWAVE: Controller status: Scan completed
2021-05-25 18:23:34.421 INFO ZWAVE: Network scan complete. Found: 2 nodes
2021-05-25 18:23:36.893 INFO APP: GET /control-panel 200 18.140 ms - 1371
2021-05-25 18:23:36.966 INFO APP: GET /static/css/app.58e718f18996a85e37a0.css 200 7.520 ms - 641856
2021-05-25 18:23:37.011 INFO APP: GET /static/js/app.0f8c31dda549490b68ea.js 200 6.202 ms - 1811249
2021-05-25 18:23:37.330 INFO APP: GET /api/auth-enabled 304 10.503 ms - -
2021-05-25 18:23:37.402 INFO APP: GET /static/logo.png 200 2.398 ms - 10014
2021-05-25 18:23:37.529 INFO APP: GET /static/fonts/MaterialIcons-Regular.fa3334f.woff2 200 2.882 ms - 82492
2021-05-25 18:23:37.645 INFO APP: GET /api/settings 304 111.439 ms - -
2021-05-25 18:23:37.653 INFO APP: GET /static/favicons/favicon-32x32.png 200 1.395 ms - 1831
2021-05-25 18:23:37.692 INFO APP: GET /api/auth-enabled 304 17.451 ms - -
2021-05-25 18:23:49.072 WARN APP: Shutdown detected: closing clients...
2021-05-25 18:23:49.074 INFO GATEWAY: Closing Gateway...
2021-05-25 18:23:49.095 INFO ZWAVE-SERVER: Server closed
2021-05-25 18:23:49.098 INFO ZWAVE-SERVER: Client disconnected
2021-05-25 18:23:49.120 INFO ZWAVE: Client closed
```
and logs post downgrade to 4.3.1:
```
2021-05-25 18:23:56.635 INFO ZWAVE: Next update scheduled for: Wed May 26 2021 00:00:00 GMT+0000 (Coordinated Universal Time)
2021-05-25 18:23:59.361 INFO APP: GET /control-panel 304 16.296 ms - -
2021-05-25 18:23:59.489 INFO APP: GET /static/css/app.58e718f18996a85e37a0.css 304 11.129 ms - -
2021-05-25 18:23:59.491 INFO APP: GET /static/js/app.0f8c31dda549490b68ea.js 304 9.318 ms - -
2021-05-25 18:23:59.783 INFO APP: GET /api/auth-enabled 304 6.356 ms - -
2021-05-25 18:23:59.880 INFO APP: GET /static/logo.png 304 1.156 ms - -
2021-05-25 18:24:00.047 INFO APP: GET /static/fonts/MaterialIcons-Regular.fa3334f.woff2 304 4.813 ms - -
2021-05-25 18:24:00.182 INFO APP: GET /api/settings 200 138.095 ms - 1192
2021-05-25 18:24:00.189 INFO APP: GET /static/favicons/favicon-32x32.png 304 4.409 ms - -
2021-05-25 18:24:00.196 INFO ZWAVE: Zwave driver is ready
2021-05-25 18:24:00.198 INFO ZWAVE: Controller status: Driver ready
2021-05-25 18:24:00.206 INFO ZWAVE: Scanning network with homeid: 0xde677210
2021-05-25 18:24:00.208 INFO ZWAVE: Node 1 is alive
2021-05-25 18:24:00.257 INFO ZWAVE-SERVER: ZwaveJS server listening on port 3000
2021-05-25 18:24:00.279 INFO APP: GET /api/auth-enabled 304 1.923 ms - -
2021-05-25 18:24:00.303 INFO ZWAVE: Node 1 ready: AEON Labs - ZW090 (Z‐Stick Gen5 USB Controller)
2021-05-25 18:24:03.778 INFO ZWAVE: Node 5 is dead
2021-05-25 18:24:03.780 INFO ZWAVE: Controller status: Scan completed
2021-05-25 18:24:03.781 INFO ZWAVE: Network scan complete. Found: 2 nodes
2021-05-25 18:24:17.072 INFO ZWAVE: Node 5: has returned from the dead
2021-05-25 18:24:17.149 INFO ZWAVE: Node 5: value added 5-98-0-currentMode => 255
2021-05-25 18:24:17.153 INFO ZWAVE: Node 5: value added 5-98-0-targetMode => 0
2021-05-25 18:24:17.154 INFO ZWAVE: Node 5: value added 5-98-0-outsideHandlesCanOpenDoor => false,false,false,false
2021-05-25 18:24:17.155 INFO ZWAVE: Node 5: value added 5-98-0-insideHandlesCanOpenDoor => false,false,false,false
2021-05-25 18:24:17.156 INFO ZWAVE: Node 5: value added 5-98-0-latchStatus => open
2021-05-25 18:24:17.156 INFO ZWAVE: Node 5: value added 5-98-0-boltStatus => locked
2021-05-25 18:24:17.157 INFO ZWAVE: Node 5: value added 5-98-0-doorStatus => closed
2021-05-25 18:24:17.157 INFO ZWAVE: Node 5: value added 5-98-0-lockTimeout => 0
2021-05-25 18:24:17.158 INFO ZWAVE: Node 5: value added 5-98-0-operationType => 1
2021-05-25 18:24:17.158 INFO ZWAVE: Node 5: value added 5-98-0-outsideHandlesCanOpenDoorConfiguration => false,false,false,false
2021-05-25 18:24:17.159 INFO ZWAVE: Node 5: value added 5-98-0-insideHandlesCanOpenDoorConfiguration => false,false,false,false
2021-05-25 18:24:17.159 INFO ZWAVE: Node 5: value added 5-98-0-lockTimeoutConfiguration => undefined
2021-05-25 18:24:17.160 INFO ZWAVE: Node 5: value added 5-112-0-1 => 3
2021-05-25 18:24:17.160 INFO ZWAVE: Node 5: value added 5-112-0-2 => 255
2021-05-25 18:24:17.161 INFO ZWAVE: Node 5: value added 5-112-0-3 => 30
2021-05-25 18:24:17.161 INFO ZWAVE: Node 5: value added 5-112-0-4 => 5
2021-05-25 18:24:17.162 INFO ZWAVE: Node 5: value added 5-112-0-7 => 180
2021-05-25 18:24:17.162 INFO ZWAVE: Node 5: value added 5-113-0-alarmType => 144
2021-05-25 18:24:17.163 INFO ZWAVE: Node 5: value added 5-113-0-alarmLevel => 3
2021-05-25 18:24:17.163 INFO ZWAVE: Node 5: value added 5-113-0-Access Control-Lock state => 11
2021-05-25 18:24:17.164 INFO ZWAVE: Node 5: value added 5-114-0-manufacturerId => 297
2021-05-25 18:24:17.164 INFO ZWAVE: Node 5: value added 5-114-0-productType => 26112
2021-05-25 18:24:17.165 INFO ZWAVE: Node 5: value added 5-114-0-productId => 2
2021-05-25 18:24:17.165 INFO ZWAVE: Node 5: value added 5-128-0-level => 100
2021-05-25 18:24:17.166 INFO ZWAVE: Node 5: value added 5-128-0-isLow => false
2021-05-25 18:24:17.166 INFO ZWAVE: Node 5: value added 5-134-0-libraryType => 3
2021-05-25 18:24:17.167 INFO ZWAVE: Node 5: value added 5-134-0-protocolVersion => 4.61
2021-05-25 18:24:17.167 INFO ZWAVE: Node 5: value added 5-134-0-firmwareVersions => 33.16
2021-05-25 18:24:17.168 INFO ZWAVE: Node 5: value added 5-134-0-hardwareVersion => undefined
2021-05-25 18:24:17.168 INFO ZWAVE: Node 5: value added 5-139-0-dateAndTime => undefined
2021-05-25 18:24:17.175 INFO ZWAVE: Node 5 ready: Yale - SD-L1000-CH (Conexis L1)
2021-05-25 18:24:17.199 INFO ZWAVE: Node 5: value updated: 98-0-currentMode 255 => 0
2021-05-25 18:24:17.201 INFO ZWAVE: Node 5: value updated: 98-0-outsideHandlesCanOpenDoor false,false,false,false => true,false,false,false
2021-05-25 18:24:17.202 INFO ZWAVE: Node 5: value updated: 98-0-insideHandlesCanOpenDoor false,false,false,false => false,false,false,false
2021-05-25 18:24:17.203 INFO ZWAVE: Node 5: value updated: 98-0-latchStatus open => open
2021-05-25 18:24:17.205 INFO ZWAVE: Node 5: value updated: 98-0-boltStatus locked => unlocked
2021-05-25 18:24:17.206 INFO ZWAVE: Node 5: value updated: 98-0-doorStatus closed => open
2021-05-25 18:24:18.059 INFO ZWAVE: Node 5: value updated: 98-0-currentMode 0 => 0
2021-05-25 18:24:18.065 INFO ZWAVE: Node 5 CC Notification {
type: 6,
event: 2,
label: 'Access Control',
eventLabel: 'Manual unlock operation',
parameters: undefined
}
2021-05-25 18:24:36.049 INFO ZWAVE: Node 5: value updated: 98-0-currentMode 0 => 255
2021-05-25 18:24:36.051 INFO ZWAVE: Node 5: value updated: 98-0-outsideHandlesCanOpenDoor true,false,false,false => false,false,false,false
2021-05-25 18:24:36.052 INFO ZWAVE: Node 5: value updated: 98-0-insideHandlesCanOpenDoor false,false,false,false => false,false,false,false
2021-05-25 18:24:36.054 INFO ZWAVE: Node 5: value updated: 98-0-latchStatus open => open
2021-05-25 18:24:36.055 INFO ZWAVE: Node 5: value updated: 98-0-boltStatus unlocked => locked
2021-05-25 18:24:36.057 INFO ZWAVE: Node 5: value updated: 98-0-doorStatus open => closed
2021-05-25 18:24:36.058 INFO ZWAVE: Node 5: value updated: 98-0-lockTimeout 0 => 0
2021-05-25 18:24:37.038 INFO ZWAVE: Node 5: value updated: 98-0-currentMode 255 => 255
2021-05-25 18:24:37.040 INFO ZWAVE: Node 5 CC Notification {
type: 6,
event: 1,
label: 'Access Control',
eventLabel: 'Manual lock operation',
parameters: undefined
}
```

**Comment by AlCalzone** [comment]
> Status NoAck

The device does not acknowledge the commands we send it. Usually there's nothing the host software can do about that. Just to be sure this isn't due to a recent change, please make a zwave-js (driver) log when you try to control it - both versions please.
