### ISSUE TITLE
[bug] Docker version greater than 4.2.0 fail to start

### ISSUE THREAD

**Issue by doguitar** [zwave-js/zwavejs2mqtt#1300]
Build/Run method
  Docker

zwavejs2mqtt: 4.2.1
zwave-js: 7.4.0

### Describe the bug

Server fails to start on any docker tag greater than 4.2.0.

### To Reproduce

1. Change Docker tag to latest

### Expected behavior

Server should start

### Additional context

Docker output is as follows:

```
 [90m2021-06-02 15:25:13.757 [39m  [33mWARN [39m  [1mSTORE [22m: scenes.json not found
/bin/sh: git: not found
 [90m2021-06-02 15:25:14.179 [39m  [32mINFO [39m  [1mAPP [22m: Version: 4.2.1
 [90m2021-06-02 15:25:14.179 [39m  [32mINFO [39m  [1mAPP [22m: Application path:/usr/src/app
 [90m2021-06-02 15:25:14.201 [39m  [32mINFO [39m  [1mMQTT [22m: MQTT is disabled
 [90m2021-06-02 15:25:14.211 [39m  [32mINFO [39m  [1mZWAVE [22m: Connecting to /dev/ttyACM0
Logging to file:
/usr/src/app/store/zwavejs_1.log_2021-06-02.log
 [90m2021-06-02 15:25:14.221 [39m  [32mINFO [39m  [1mAPP [22m: Listening on port 8091 host 0.0.0.0 protocol HTTP
 [90m2021-06-02 15:25:14.224 [39m  [32mINFO [39m  [1mZWAVE [22m: Zwavejs usage statistics ENABLED
 [90m2021-06-02 15:25:14.646 [39m  [32mINFO [39m  [1mZWAVE [22m: Next update scheduled for: Thu Jun 03 2021 00:00:00 GMT-0700 (Pacific Daylight Time)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'writeHead' of undefined
at sendErrorMessage (/usr/src/app/node_modules/engine.io/lib/server.js:568:7)
at Server.handshake (/usr/src/app/node_modules/engine.io/lib/server.js:291:7)
at Server.onWebSocket (/usr/src/app/node_modules/engine.io/lib/server.js:460:12)
at /usr/src/app/node_modules/engine.io/lib/server.js:401:14
at WebSocketServer.completeUpgrade (/usr/src/app/node_modules/ws/lib/websocket-server.js:330:5)
at WebSocketServer.handleUpgrade (/usr/src/app/node_modules/ws/lib/websocket-server.js:246:10)
at /usr/src/app/node_modules/engine.io/lib/server.js:400:15
at Server.verify (/usr/src/app/node_modules/engine.io/lib/server.js:131:14)
at Server.handleUpgrade (/usr/src/app/node_modules/engine.io/lib/server.js:384:10)
at Server.<anonymous> (/usr/src/app/node_modules/engine.io/lib/server.js:511:16)
```

settings.json is as follows:

```{
	"mqtt": {
		"name": "zwavejs2mqtt",
		"host": "localhost",
		"port": 1883,
		"qos": 1,
		"prefix": "zwave",
		"reconnectPeriod": 3000,
		"retain": true,
		"clean": true,
		"auth": false,
		"_ca": "",
		"ca": "",
		"_cert": "",
		"cert": "",
		"_key": "",
		"key": "",
		"disabled": true
	},
	"gateway": {
		"type": 0,
		"plugins": [],
		"authEnabled": false,
		"payloadType": 0,
		"nodeNames": true,
		"hassDiscovery": false,
		"discoveryPrefix": "homeassistant",
		"logEnabled": true,
		"logLevel": "silly",
		"logToFile": true,
		"values": []
	},
	"zwave": {
		"commandsTimeout": 30,
		"logLevel": "silly",
		"logToFile": true,
		"serverEnabled": true,
		"serverPort": 3000,
		"logEnabled": true,
		"networkKey": "527FB7F54D957-------------------------",
		"port": "/dev/ttyACM0",
		"enableStatistics": true,
		"disclaimerVersion": 1
	}
}
```

zwavejs2mqtt log is as follows:

```
2021-06-02 15:25:14.211 INFO ZWAVE: Connecting to /dev/ttyACM0
2021-06-02 15:25:14.202 INFO MQTT: MQTT is disabled
2021-06-02 15:25:14.221 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
2021-06-02 15:25:14.225 INFO ZWAVE: Zwavejs usage statistics ENABLED
2021-06-02 15:25:14.646 INFO ZWAVE: Next update scheduled for: Thu Jun 03 2021 00:00:00 GMT-0700 (Pacific Daylight Time)```

zwavejs_1.....log is as follows:

```2021-06-02T22:23:17.669Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2021-06-02T22:23:17.669Z DRIVER   version 7.4.0
2021-06-02T22:23:17.669Z CONFIG   version 7.4.0
2021-06-02T22:23:17.669Z DRIVER   
2021-06-02T22:23:17.669Z DRIVER   starting driver...
2021-06-02T22:23:17.676Z DRIVER   opening serial port /dev/ttyACM0
2021-06-02T22:23:17.684Z DRIVER   serial port opened
2021-06-02T22:23:17.685Z SERIAL » [NAK]                                                                   (0x15)
2021-06-02T22:23:17.686Z DRIVER   Checking for configuration updates...
2021-06-02T22:23:17.709Z SERIAL « 0x0110000400090a3202a1423092003d3070e4                              (18 bytes)
2021-06-02T22:23:17.711Z DRIVER   Dropping message because the driver is not ready to handle it yet.
2021-06-02T22:23:17.711Z SERIAL » [ACK]                                                                   (0x06)
2021-06-02T22:23:18.097Z DRIVER   No configuration update available...
2021-06-02T22:23:18.343Z DRIVER   destroying driver instance...```

**Comment by robertsLando** [comment]
@doguitar Could you try to startup without the settings and import them after the application starts from the ui? Also please use latest version

**Comment by doguitar** [comment]
Changing the docker tag to latest and moving settings.json (and also nodes.json afterward) had no change.

``` [90m2021-06-03 10:13:02.430 [39m  [33mWARN [39m  [1mSTORE [22m: settings.json not found
 [90m2021-06-03 10:13:02.431 [39m  [33mWARN [39m  [1mSTORE [22m: scenes.json not found
 [90m2021-06-03 10:13:02.432 [39m  [33mWARN [39m  [1mSTORE [22m: nodes.json not found
/bin/sh: git: not found
 [90m2021-06-03 10:13:02.893 [39m  [32mINFO [39m  [1mAPP [22m: Version: 4.5.1
 [90m2021-06-03 10:13:02.893 [39m  [32mINFO [39m  [1mAPP [22m: Application path:/usr/src/app
 [90m2021-06-03 10:13:02.910 [39m  [31mERROR [39m  [1mGATEWAY [22m: Zwave settings are not valid
 [90m2021-06-03 10:13:02.912 [39m  [32mINFO [39m  [1mAPP [22m: Listening on port 8091 host 0.0.0.0 protocol HTTP
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'writeHead' of undefined
at sendErrorMessage (/usr/src/app/node_modules/engine.io/lib/server.js:568:7)
at Server.handshake (/usr/src/app/node_modules/engine.io/lib/server.js:291:7)
at Server.onWebSocket (/usr/src/app/node_modules/engine.io/lib/server.js:460:12)
at /usr/src/app/node_modules/engine.io/lib/server.js:401:14
at WebSocketServer.completeUpgrade (/usr/src/app/node_modules/ws/lib/websocket-server.js:330:5)
at WebSocketServer.handleUpgrade (/usr/src/app/node_modules/ws/lib/websocket-server.js:246:10)
at /usr/src/app/node_modules/engine.io/lib/server.js:400:15
at Server.verify (/usr/src/app/node_modules/engine.io/lib/server.js:131:14)
at Server.handleUpgrade (/usr/src/app/node_modules/engine.io/lib/server.js:384:10)
at Server.<anonymous> (/usr/src/app/node_modules/engine.io/lib/server.js:511:16)
 ```

Here is my docker command as well:
```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d 
--name='zwave2mqtt-js' 
--net='bridge' 
-e TZ="America/Los_Angeles" 
-e HOST_OS="Unraid" 
-e 'OZW_NETWORK_KEY'='527FB7F54D----------------' 
-p '8095:8091/tcp' 
-p '8103:3000/tcp' 
-v '/mnt/user/appdata/zwave2mqtt':'/usr/src/app/store':'rw' 
--device='/dev/ttyACM0' 
--cpu-shares 2048 
--restart unless-stopped 
'zwavejs/zwavejs2mqtt:latest'
```

**Comment by doguitar** [comment]
I created a brand new instance from scratch to try and find the issue and everything worked as expected until I changed the webui port mapping to my original port, `8095` then it broke. I remapped my original image's port to another port and it started right up.

**Comment by robertsLando** [comment]
So the problem seems related to the different port used?

**Comment by doguitar** [comment]
Yes. I changed `-p '8095:8091/tcp' ` to `-p '8108:8091/tcp' ` and it starts up normally.

I just tested changing it back to `-p '8095:8091/tcp' ` and it crashes again with the same error message.

**Comment by robertsLando** [comment]
Could be related to https://github.com/socketio/engine.io/commit/43606865e5299747cbb31f3ed9baf4567502a879
