### ISSUE TITLE
[HASS] cover device 'value_template' deprecated?

### ISSUE THREAD

**Issue by bushvin** [zwave-js/zwavejs2mqtt#1327]
### Version
HA 2021.6.3

Run method: Docker

zwavejs2mqtt: 5.0.0
zwave-js: 7.7.3

### Describe the bug
Fibaro fgr222 cover 'disappeared' after upgrading HA to 2021.6.3
Resulting in the following error in home assistant:
```txt
2021-06-11 00:25:48 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'command_topic': 'zwave/fibaro_fgr222_00/38/0/targetValue/set', 'position_topic': 'zwave/fibaro_fgr222_00/38/0/currentValue', 'set_position_topic': 'zwave/fibaro_fgr222_00/38/0/targetValue/set', 'value_template': '{{ (value_json.value / 99 * 100) | round(0) }}', 'position_open': 99, 'position_closed': 0, 'payload_open': '99', 'payload_close': '0', 'device': {'identifiers': ['zwavejs2mqtt_0xc883eb3e_node18'], 'manufacturer': 'Fibargroup', 'model': 'Roller Shutter 2 (FGR222)', 'name': 'fibaro_fgr222_00', 'sw_version': '25.25'}, 'name': 'fibaro_fgr222_00_position', 'unique_id': 'zwavejs2mqtt_0xc883eb3e_Node18_position', 'platform': 'mqtt'},)

Traceback (most recent call last):                                                                            
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)                                                                           
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)                                                                                       
File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options
    raise vol.Invalid(
voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'.                                                                                                                                     

During handling of the above exception, another exception occurred:
                                                                                                            
Traceback (most recent call last):                                                                            
File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover
    config = schema(discovery_payload)                                                                        
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)                                            
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)                                                                                               
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])                                                                           
voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
```

Apparently 2021.6.3 breaks mqtt in certain cases:
> Using `value_template` to use for extracting position is no longer allowed an error will be raised if this configuration is used, Instead of using `value_template`, `position_template` should be used.

[Source](https://www.home-assistant.io/blog/2021/06/02/release-20216/#other-breaking-changes)

Based on an [issue](https://github.com/Koenkk/zigbee2mqtt/issues/7680) for zigbee2mqtt, is this something that needs fixing in zwavejs2mqtt?

**Comment by robertsLando** [comment]
Yep, seems that the fix needed is: 

> Using value_template to use for extracting position is no longer allowed an error will be raised if this configuration is used, Instead of using value_template, position_template should be used.

**Comment by bushvin** [comment]
Thank you very much for the swift response!

**Comment by bushvin** [comment]
Do I need to clear something to get this working?
I updated the docker image to 5.0.1, removed my mosquitto db and cleaned the device and related entities, yet the same error persists.

When rediscovering the node, this is the result:
```json
{
  "type": "cover",
  "object_id": "position",
  "values": [
    "38-0-currentValue",
    "38-0-targetValue"
  ],
  "discovery_payload": {
    "command_topic": "zwave/fibaro_fgr222_00/38/0/targetValue/set",
    "position_topic": "zwave/fibaro_fgr222_00/38/0/currentValue",
    "set_position_topic": "zwave/fibaro_fgr222_00/38/0/targetValue/set",
    "value_template": "{{ (value_json.value / 99 * 100) | round(0) }}",
    "position_open": 99,
    "position_closed": 0,
    "payload_open": "99",
    "payload_close": "0",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc883eb3e_node18"
      ],
      "manufacturer": "Fibargroup",
      "model": "Roller Shutter 2 (FGR222)",
      "name": "fibaro_fgr222_00",
      "sw_version": "25.25"
    },
    "name": "fibaro_fgr222_00_position",
    "unique_id": "zwavejs2mqtt_0xc883eb3e_Node18_position"
  },
  "discoveryTopic": "cover/fibaro_fgr222_00/position/config",
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "cover_position"
}
```

As you can see `value_template` is still there...
I've manually updated the `value_template` to `position_template`, to see what happens...

**Comment by bushvin** [comment]
I believe there was one entry you may have omitted.
I updated it and submnitted a PR #1336

**Comment by robertsLando** [comment]
Thanks for the PR!
