### ISSUE TITLE
[bug] TypeError: states is not iterable on z2m logs after upgrading to 5.0.0

### ISSUE THREAD

**Issue by xhemp** [zwave-js/zwavejs2mqtt#1332]
### Version

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [X] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.0
zwave-js version: 7.7.3

### Describe the bug

Geting errors on z2m logs that I was not getting before on 4.5.2:
`2021-06-11 10:17:44.607 ERROR GATEWAY: Error while discovering value 59-113-0-alarmType of node 59: states is not iterable states is not iterable

    at Gateway._getMappedStateTemplate (/home/hass/zwavejs2mqtt/server/lib/Gateway.js:1677:25)
    at Gateway.discoverValue (/home/hass/zwavejs2mqtt/server/lib/Gateway.js:1051:34)
    at Gateway._onNodeStatus (/home/hass/zwavejs2mqtt/server/lib/Gateway.js:1412:22)
    at ZwaveClient.emit (events.js:315:20)
    at ZwaveClient.EventEmitter.emit (domain.js:482:12)
    at ZwaveClient._onNodeStatus (/home/hass/zwavejs2mqtt/server/lib/ZwaveClient.js:1472:18)
    at ZwaveClient._onNodeSleep (/home/hass/zwavejs2mqtt/server/lib/ZwaveClient.js:1579:14)
    at ZWaveNode.emit (events.js:327:22)
    at ZWaveNode.EventEmitter.emit (domain.js:482:12)
    at ZWaveNode.onStatusChange (/home/hass/zwavejs2mqtt/node_modules/zwave-js/src/lib/node/Node.ts:391:9)
2021-06-11 10:17:44.610 ERROR GATEWAY: Error while discovering value 59-113-0-alarmLevel of node 59: states is not iterable states is not iterable
TypeError: states is not iterable

    at Gateway._getMappedStateTemplate (/home/hass/zwavejs2mqtt/server/lib/Gateway.js:1677:25)
    at Gateway.discoverValue (/home/hass/zwavejs2mqtt/server/lib/Gateway.js:1051:34)
    at Gateway._onNodeStatus (/home/hass/zwavejs2mqtt/server/lib/Gateway.js:1412:22)
    at ZwaveClient.emit (events.js:315:20)
    at ZwaveClient.EventEmitter.emit (domain.js:482:12)
    at ZwaveClient._onNodeStatus (/home/hass/zwavejs2mqtt/server/lib/ZwaveClient.js:1472:18)
    at ZwaveClient._onNodeSleep (/home/hass/zwavejs2mqtt/server/lib/ZwaveClient.js:1579:14)
    at ZWaveNode.emit (events.js:327:22)
    at ZWaveNode.EventEmitter.emit (domain.js:482:12)
    at ZWaveNode.onStatusChange (/home/hass/zwavejs2mqtt/node_modules/zwave-js/src/lib/node/Node.ts:391:9)`

They look to be happening constantly as I still see them long after z2m is started.
Full dump is attached
[dump_11062021.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6637502/dump_11062021.json.txt)

### To Reproduce

I have just updated from 4.5.2 to 5.0.0, on 4.5.2, I wasn't seeing this happening.

### Expected behavior

No errors

**Comment by xhemp** [comment]
Instrospecting a bit more of the logs, I can see it is happening with a Yale Lock and a motion sensor always on CC 113 and also only with Alarm Type and Alarm Level.

> 2021-06-10 22:45:09.879 ERROR GATEWAY: Error while discovering value 59-113-0-alarmType of node 59: states is not iterable states is not iterable
2021-06-10 22:45:09.882 ERROR GATEWAY: Error while discovering value 59-113-0-alarmLevel of node 59: states is not iterable states is not iterable
2021-06-10 22:45:19.924 ERROR GATEWAY: Error while discovering value 17-113-0-alarmType of node 17: states is not iterable states is not iterable
2021-06-10 22:45:19.927 ERROR GATEWAY: Error while discovering value 17-113-0-alarmLevel of node 17: states is not iterable states is not iterable
2021-06-10 22:46:08.975 ERROR GATEWAY: Error while discovering value 59-113-0-alarmType of node 59: states is not iterable states is not iterable
2021-06-10 22:46:08.979 ERROR GATEWAY: Error while discovering value 59-113-0-alarmLevel of node 59: states is not iterable states is not iterable
2021-06-10 22:46:10.128 ERROR GATEWAY: Error while discovering value 59-113-0-alarmType of node 59: states is not iterable states is not iterable
2021-06-10 22:46:10.134 ERROR GATEWAY: Error while discovering value 59-113-0-alarmLevel of node 59: states is not iterable states is not iterable
