### ISSUE TITLE
[bug] semver package missing in docker image

### ISSUE THREAD

**Issue by ODINServ** [zwave-js/zwavejs2mqtt#15]
podman run --rm -it -p 8091:8091 --device=/dev/ttyACM0 -v zwave-js:/usr/src/app/store zwavejs/zwavejs2mqtt:dev

Results in an error:
Error: Cannot find module 'semver'

Workaround for me was to rebuild the image and add the semver package:
```
FROM docker.io/zwavejs/zwavejs2mqtt:dev
RUN /usr/local/bin/npm install semver
```

**Comment by robertsLando** [comment]
@ODINServ I think this isn't a bug anymore as it was caused by a broken zwave-js version. Feel free to reopen if I'm wrong

**Comment by ODINServ** [comment]
Hey,

It is still not working for me, i also see that the image was lased pushed 4 days ago on docker hub?

I did remove the old "dev" image locally, see commandline output:

[ltm ~]# podman run -it zwavejs/zwavejs2mqtt:dev
Trying to pull docker.io/zwavejs/zwavejs2mqtt:dev...
Getting image source signatures
Copying blob 9287919c3a0f skipped: already exists  
Copying blob cbdbe7a5bc2a skipped: already exists  
Copying blob 3c1bcea295c4 skipped: already exists  
Copying blob 43a47bbd54c9 skipped: already exists  
Copying blob fdea6a67e12b done  
Copying blob ff2639f90704 done  
Copying config b90e228377 done  
Writing manifest to image destination
Storing signatures
  z2m:Store settings.json not found +0ms
  z2m:Store scenes.json not found +2ms
  z2m:Store nodes.json not found +1ms
Error: Cannot find module 'semver'
Require stack:
- /usr/src/app/node_modules/@zwave-js/config/build/utils.js
- /usr/src/app/node_modules/@zwave-js/config/build/DeviceClasses.js
- /usr/src/app/node_modules/@zwave-js/config/build/index.js
- /usr/src/app/node_modules/zwave-js/build/lib/commandclass/IndicatorCC.js
- /usr/src/app/node_modules/zwave-js/build/lib/commandclass/index.js
- /usr/src/app/node_modules/zwave-js/CommandClass.js
- /usr/src/app/node_modules/zwave-js/index.js
- /usr/src/app/lib/ZwaveClient.js
- /usr/src/app/node_modules/app-root-path/lib/app-root-path.js
- /usr/src/app/node_modules/app-root-path/index.js
- /usr/src/app/bin/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@zwave-js/config/src/utils.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@zwave-js/config/src/DeviceClasses.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/@zwave-js/config/build/utils.js',
    '/usr/src/app/node_modules/@zwave-js/config/build/DeviceClasses.js',
    '/usr/src/app/node_modules/@zwave-js/config/build/index.js',
    '/usr/src/app/node_modules/zwave-js/build/lib/commandclass/IndicatorCC.js',
    '/usr/src/app/node_modules/zwave-js/build/lib/commandclass/index.js',
    '/usr/src/app/node_modules/zwave-js/CommandClass.js',
    '/usr/src/app/node_modules/zwave-js/index.js',
    '/usr/src/app/lib/ZwaveClient.js',
    '/usr/src/app/node_modules/app-root-path/lib/app-root-path.js',
    '/usr/src/app/node_modules/app-root-path/index.js',
    '/usr/src/app/bin/www'
  ]
}
[ltm ~]

**Comment by robertsLando** [comment]
@ODINServ

**Comment by robertsLando** [comment]
@ODINServ try in 30 minutes when the build finish

**Comment by ODINServ** [comment]
It works!

The dev image and the last tag!

Thnx

**Comment by robertsLando** [comment]
@ODINServ You welcome! Keep testing and let me know if you find some other bugs
