### ISSUE TITLE
[question] Getting build errors when following development instructions

### ISSUE THREAD

**Issue by AlfHou** [zwave-js/zwavejs2mqtt#1563]
I'm trying to set up the project for development following these [instructions](https://zwave-js.github.io/zwavejs2mqtt/#/development/intro). However I get this error when running `yarn run dev`. I've tried running `yarn install` beforehand as well.
I've tried on both my Mac and my Linux box

```
yarn run v1.22.11
$ webpack serve --inline --progress --host 0.0.0.0 --config build/webpack.dev.conf.js
[webpack-cli] Failed to load '/home/alf/Source/zwavejs2mqtt/build/webpack.dev.conf.js' config
[webpack-cli] Error: Cannot find module '../server/config/webConfig'
Require stack:
- /home/alf/Source/zwavejs2mqtt/build/webpack.dev.conf.js
- /home/alf/Source/zwavejs2mqtt/node_modules/webpack-cli/lib/webpack-cli.js
- /home/alf/Source/zwavejs2mqtt/node_modules/webpack-cli/lib/bootstrap.js
- /home/alf/Source/zwavejs2mqtt/node_modules/webpack-cli/bin/cli.js
- /home/alf/Source/zwavejs2mqtt/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/home/alf/Source/zwavejs2mqtt/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/alf/Source/zwavejs2mqtt/build/webpack.dev.conf.js:5:23)
    at Module._compile (/home/alf/Source/zwavejs2mqtt/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/alf/Source/zwavejs2mqtt/build/webpack.dev.conf.js',
    '/home/alf/Source/zwavejs2mqtt/node_modules/webpack-cli/lib/webpack-cli.js',
    '/home/alf/Source/zwavejs2mqtt/node_modules/webpack-cli/lib/bootstrap.js',
    '/home/alf/Source/zwavejs2mqtt/node_modules/webpack-cli/bin/cli.js',
    '/home/alf/Source/zwavejs2mqtt/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 2.
```

**Comment by robertsLando** [comment]
Could you show me all the commands you have run in order?

**Comment by AlfHou** [comment]
I tried running `yarn install` then `yarn run dev` which resulted in the error above.

If I try only running `yarn run dev` as it says in the documentation, I get the following error
```
$ webpack serve --inline --progress --host 0.0.0.0 --config build/webpack.dev.conf.js
[webpack-cli] Error: Unknown option '--inline'
[webpack-cli] Run 'webpack --help' to see available commands and options
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This is after installing `webpack`, `webpack-cli` and `webpack-dev-server`,  using `yarn global add webpack`, `yarn global add webpack-cli` and `yarn global add webpack-dev-server`

**Comment by robertsLando** [comment]
You don't have to install webpack etc globally, the steps are 

```
git clone https://github.com/zwave-js/zwavejs2mqtt
cd zwavejs2mqtt
yarn install
yarn run build
yarn start
```

**Comment by AlfHou** [comment]
Ah, perfect! Should I update the development instructions [here](https://zwave-js.github.io/zwavejs2mqtt/#/development/intro) then?

**Comment by robertsLando** [comment]
You just were looking at the wrong docs: https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start?id=nodejs-or-pkg-version
