### ISSUE TITLE
[bug] Enabling zwave-js integration in HA causes WS client socket disconnects UNTIL a network re-interview is performed in the control panel

### ISSUE THREAD

**Issue by nfrntrd** [zwave-js/zwavejs2mqtt#1769]
Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 5.7.2
zwave-js: 8.4.1
home id: 3897765872
home hex: 0xe8532ff0

### Describe the bug

Recently I moved from legacy zwave 1.4 integration and moved to the zwave-js integration.  In my development system which has an identical Aeotec Gen5 stick with one device included, everything integrated perfectly into HA.  Nice job development team!

When I went to extend that to my production zwave environment which has 41 nodes in it, I immediately got client disconnects from the websocket side of zwavejs2mqtt.  I got frustrated and tried docker/pkg/snap and the same result for each.  Then by chance when I attempted to re-interview the nodes in the control panel, the disconnects from the WS went away and HA prod could talk to the WS server.  It will continue to work until you either attempt to restart HA or upgrade docker container of zwavejs2mqtt.  Then the problem starts all over again until a re-interview of all nodes is done.  

From the template instructions: 
Home Assistant -> settings -> Integrations -> Z-Wave JS -> Configure -> Create dump -> zip the json file and post it here.

I tried to perform the action above but the message in Home Assistant log gave me below there was a zero byte file download.

2021-10-01 12:12:30 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/ha/homeassistant/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/ha/homeassistant/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/ha/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/home/ha/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/forwarded.py", line 211, in forwarded_middleware
    return await handler(request)
  File "/home/ha/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/home/ha/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/home/ha/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/home/ha/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/home/ha/homeassistant/lib/python3.8/site-packages/homeassistant/components/zwave_js/api.py", line 1286, in get
    msgs = await dump.dump_msgs(entry.data[CONF_URL], async_get_clientsession(hass))
  File "/home/ha/homeassistant/lib/python3.8/site-packages/zwave_js_server/dump.py", line 31, in dump_msgs
    msgs.append(await client.receive_json())
  File "/home/ha/homeassistant/lib/python3.8/site-packages/aiohttp/client_ws.py", line 291, in receive_json
    data = await self.receive_str(timeout=timeout)
  File "/home/ha/homeassistant/lib/python3.8/site-packages/aiohttp/client_ws.py", line 276, in receive_str
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not str")
TypeError: Received message 258:WebSocketError(<WSCloseCode.MESSAGE_TOO_BIG: 1009>, 'Message size 5517414 exceeds limit 4194304') is not str

Attached is a zip:
home-assistant.log to show the disconnects from the HA side until I perform a re-interview
the zwavejs2mqtt and zwavejs log files from the WS server side.  Of note: the disconnects start at 16:57 (on the docker container side) - sorry TZ wasn't set.  You'll see it as 11:57 on the home-assistant.log side
nodes_dump.json to show my nodes in production

Could it be there is some crazy output in my 41 nodes that makes the WS server choke on the side of the message?  Or is aiohttp on my system screwed up due to message size?  I'm using 2021.9.7 of HA.

[home-assistant.log](https://github.com/zwave-js/zwavejs2mqtt/files/7269145/home-assistant.log)
[zwavejs2mqttlogs.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7269173/zwavejs2mqttlogs.zip)

Thank you for any help.  If I should file this elsewhere in an HA bug report, I apologize in advance. 

### To Reproduce
Upgrade docker or restart HA. Re-interview the nodes in the control panel and the disconnects from the WS go away and HA prod can talk to the WS server.  It will continue to work until you either attempt to restart HA or upgrade docker container of zwavejs2mqtt.  

### Expected behavior

If / when I restart HA or upgrade zwavejs2mqtt docker container, I expect the WS to reconnect without issue.

**Comment by nfrntrd** [comment]
In the zwavejs2mqtt log at 16:58:20 this might tell you something, but I don't know what it means.  I know that's the time I instructed the re-interview.

2021-10-01 16:54:39.160 INFO ZWAVE: Node 4: value updated: 38-0-currentValue 99 => 0
2021-10-01 16:54:46.626 INFO ZWAVE: Node 4: value updated: 38-0-currentValue 0 => 99
2021-10-01 16:56:47.367 INFO ZWAVE: Node 2: value updated: 32-0-currentValue 255 => 0
2021-10-01 16:56:47.639 INFO ZWAVE: Node 2: value updated: 113-0-Home Security-Motion sensor status 8 => 0
2021-10-01 16:57:12.439 INFO ZWAVE: Node 2: value updated: 32-0-currentValue 0 => 255
2021-10-01 16:57:12.701 INFO ZWAVE: Node 2: value updated: 113-0-Home Security-Motion sensor status 0 => 8
2021-10-01 16:58:20.657 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.658 INFO ZWAVE: Calling api refreshInfo with args: [ 1, [length]: 1 ]
2021-10-01 16:58:20.658 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.661 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.664 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.666 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.668 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.670 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.674 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.678 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.679 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.681 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.683 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.685 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.687 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.689 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.691 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.694 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.697 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.699 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.702 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.703 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.705 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.707 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.708 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.709 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.711 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.712 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.714 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.715 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.717 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.718 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.720 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.721 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.722 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.724 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.724 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.725 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.725 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.726 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.726 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.727 DEBUG SOCKET: Event ZWAVE_API emitted to P7LY5PBjA8LkyS8WAAAF
2021-10-01 16:58:20.659 INFO ZWAVE: Calling api refreshInfo with args: [ 2, [length]: 1 ]
2021-10-01 16:58:20.662 INFO ZWAVE: Calling api refreshInfo with args: [ 3, [length]: 1 ]
2021-10-01 16:58:20.664 INFO ZWAVE: Calling api refreshInfo with args: [ 4, [length]: 1 ]

**Comment by kpine** [comment]
This problem is because you have several nodes (I couldn't count them all) that support the Scene Actuator Conf CC. Because of a change in zwave-js 8.4.0 it has greatly increased the amount of data that is sent out to websocket clients when they first connect to the server, in. In this case it's the HA Python client, and it is not configured to handle the payload size. You can see this in the nodes_dump.json file from zwavejs2mqtt, which is basically the same information, and it's 10MB, the limit being 4MB according to the stack trace. I only have a single node that supports Scene Actuator Conf CC, and that node accounts for 50% of the node state dump size for my network.

And yes, please file this bug in the HA core project instead, it is not a zwavejs2mqtt bug. This is why the bug template says:
>  1. Are you using HomeAssistant?
  If yes, please open your issue at https://github.com/home-assistant/core/issues
  UNLESS a developer told you to come here.

**Comment by kpine** [comment]
As a workaround, I think you could temporarily edit the file `/home/ha/homeassistant/lib/python3.8/site-packages/aiohttp/client_ws.py`. In the `connect()` function you can disable the message size limit, or so to whatever size you want.

```python
            self._client = await self.aiohttp_session.ws_connect(
                self.ws_server_url,
                heartbeat=55,
                max_msg_size=0,
            )                                                                                                                                                                                                                                                           )

**Comment by nfrntrd** [comment]
> This problem is because you have several nodes (I couldn't count them all) that support the Scene Actuator Conf CC. Because of a change in zwave-js 8.4.0 it has greatly increased the amount of data that is sent out to websocket clients when they first connect to the server. In this case it's the HA Python client, and it is not configured to handle the payload size. You can see this in the nodes_dump.json file from zwavejs2mqtt, which is basically the same information, and it's 10MB, the limit being 4MB according to the stack trace. I only have a single node that supports Scene Actuator Conf CC, and that node accounts for 50% of the node state dump size for my network.
> 
> And yes, please file this bug in the HA core project instead, it is not a zwavejs2mqtt bug. This is why the bug template says:
> 
> > 1. Are you using HomeAssistant?
> >    If yes, please open your issue at https://github.com/home-assistant/core/issues
> >    UNLESS a developer told you to come here.

Thank you so much for looking into it.  I will file it in HA.  This seemed so specific to my migration, but thank you for directing me to the right place.

**Comment by nfrntrd** [comment]
Closing and moving over to HA core integration.
https://github.com/home-assistant/core/issues/56922
