### ISSUE TITLE
[question]  Error ENOENT no such file or directory, for a few hours

### ISSUE THREAD

**Issue by rvb89** [zwave-js/zwavejs2mqtt#1907]
Hello,

For a few hours my setup of zwavejs2mqtt installed with snap, shows the following error when trying to access it's webpage.
I tried to restart it with snap restart zwavejs2mqtt and also reboot the server but no success.

> Error: ENOENT: no such file or directory, scandir '/snap/zwavejs2mqtt/244/lib/node_modules/zwavejs2mqtt/server/dist/static/css'
>     at Object.readdirSync (node:fs:1390:3)
>     at findFiles (/snap/zwavejs2mqtt/244/lib/node_modules/zwavejs2mqtt/server/lib/renderIndex.js:29:28)
>     at default_1 (/snap/zwavejs2mqtt/244/lib/node_modules/zwavejs2mqtt/server/lib/renderIndex.js:49:28)
>     at Layer.handle [as handle_request] (/snap/zwavejs2mqtt/244/lib/node_modules/zwavejs2mqtt/node_modules/express/lib/router/layer.js:95:5)
>     at next (/snap/zwavejs2mqtt/244/lib/node_modules/zwavejs2mqtt/node_modules/express/lib/router/route.js:137:13)
>     at /snap/zwavejs2mqtt/244/lib/node_modules/zwavejs2mqtt/node_modules/express-rate-limit/lib/express-rate-limit.js:170:15

How can I solve this ?
Thanks

**Comment by rvb89** [comment]
The error is gone
