### ISSUE TITLE
Is there a way to increase ACK timeout?

### ISSUE THREAD

**Issue by renmarq** [zwave-js/zwavejs2mqtt#2123]
My controller is new and ran fine for two weeks but now 95% of the time I get a timeout error in the logs when running a command. 

This morning it failed 5 times in a row (I only included the first):
```

 ______                       _     ___                  _   _   
|___  /                      (_)   |__ \                | | | |  
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ 
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ 
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |        
                           |__/                       |_|        

2021-12-31 09:34:02.656 WARN STORE: scenes.json not found
2021-12-31 09:34:02.678 INFO APP: HTTPS is enabled. Loading cert and keys
2021-12-31 09:34:03.009 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTPS
2021-12-31 09:34:03.168 INFO MQTT: MQTT is disabled
2021-12-31 09:34:03.200 INFO ZWAVE: Connecting to /dev/zwave
2021-12-31T09:34:03.204Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2021-12-31T09:34:03.208Z DRIVER   version 8.9.1
2021-12-31T09:34:03.210Z DRIVER   
2021-12-31T09:34:03.211Z DRIVER   starting driver...
2021-12-31T09:34:03.267Z DRIVER   opening serial port /dev/zwave
2021-12-31T09:34:03.291Z DRIVER   serial port opened
2021-12-31T09:34:03.295Z SERIAL » [NAK]                                                                   (0x15)
2021-12-31 09:34:03.304 INFO ZWAVE: Zwavejs usage statistics ENABLED
2021-12-31T09:34:03.310Z DRIVER   loading configuration...
2021-12-31T09:34:03.349Z CONFIG   Synchronizing external config dir /usr/src/app/store/.config-db...
2021-12-31T09:34:29.026Z CONFIG   Using external configuration dir /usr/src/app/store/.config-db
2021-12-31T09:34:29.028Z CONFIG   version 8.9.1
2021-12-31T09:34:47.206Z CONFIG   Device index regenerated
2021-12-31T09:34:47.208Z CONFIG   Priority device configuration directory /usr/src/app/store/config not found
2021-12-31T09:34:47.337Z DRIVER   beginning interview...
2021-12-31T09:34:47.342Z DRIVER   added request handler for AddNodeToNetwork (0x4a)...
                                  1 registered
2021-12-31T09:34:47.343Z DRIVER   added request handler for RemoveNodeFromNetwork (0x4b)...
                                  1 registered
2021-12-31T09:34:47.344Z DRIVER   added request handler for ReplaceFailedNode (0x63)...
                                  1 registered
2021-12-31T09:34:47.348Z CNTRLR   querying controller IDs...
2021-12-31T09:34:48.300Z SERIAL » 0x01030020dc                                                         (5 bytes)
2021-12-31T09:34:48.308Z DRIVER » [REQ] [GetControllerId]
2021-12-31T09:34:49.333Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-31T09:34:49.440Z SERIAL » 0x01030020dc                                                         (5 bytes)
2021-12-31T09:34:49.443Z DRIVER » [REQ] [GetControllerId]
2021-12-31T09:34:50.456Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2021-12-31T09:34:51.561Z SERIAL » 0x01030020dc                                                         (5 bytes)
2021-12-31T09:34:51.566Z DRIVER » [REQ] [GetControllerId]
2021-12-31T09:34:52.619Z DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK 
                                  from the controller (ZW0200)
                                      at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/D
                                  river.ts:3350:23)
                                      at ZWaveController.identify (/usr/src/app/node_modules/zwave-js/src/lib/co
                                  ntroller/Controller.ts:677:33)
                                      at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js
                                  /src/lib/driver/Driver.ts:977:26)
                                      at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/drive
                                  r/Driver.ts:857:16)
2021-12-31 09:34:52.625 INFO ZWAVE: Controller status: Driver: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:3350:23)
    at ZWaveController.identify (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:677:33)
    at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:977:26)
    at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:857:16) (ZW0100)
2021-12-31 09:34:52.633 INFO ZWAVE-SERVER: Server closed
2021-12-31T09:34:52.638Z DRIVER   destroying driver instance...
2021-12-31T09:34:52.649Z DRIVER   driver instance destroyed
2021-12-31 09:34:52.652 INFO ZWAVE: Client closed
```

Before eventually:
```
2021-12-31 09:35:20.155 INFO ZWAVE: Connecting to /dev/zwave
2021-12-31T09:35:20.157Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2021-12-31T09:35:20.158Z DRIVER   version 8.9.1
2021-12-31T09:35:20.159Z DRIVER   
2021-12-31T09:35:20.160Z DRIVER   starting driver...
2021-12-31T09:35:20.173Z DRIVER   opening serial port /dev/zwave
2021-12-31T09:35:20.185Z DRIVER   serial port opened
2021-12-31T09:35:20.186Z SERIAL » [NAK]                                                                   (0x15)
2021-12-31 09:35:20.190 INFO ZWAVE: Zwavejs usage statistics ENABLED
2021-12-31T09:35:20.195Z SERIAL « 0x01080120f422a77a01dc                                              (10 bytes)
2021-12-31T09:35:20.204Z SERIAL » [ACK]                                                                   (0x06)
2021-12-31T09:35:20.207Z DRIVER   loading configuration...
2021-12-31T09:35:20.212Z DRIVER « [RES] [GetControllerId]
                                    payload: 0xf422a77a01
2021-12-31T09:35:20.225Z DRIVER « [RES] [GetControllerId]                                           [unexpected]
                                    payload: 0xf422a77a01
2021-12-31T09:35:20.227Z DRIVER   unexpected response, discarding...
2021-12-31T09:35:20.233Z CONFIG   Using external configuration dir /usr/src/app/store/.config-db
2021-12-31T09:35:20.234Z CONFIG   version 8.9.1
2021-12-31T09:35:22.793Z CONFIG   Priority device configuration directory /usr/src/app/store/config not found
2021-12-31T09:35:22.910Z DRIVER   beginning interview...
2021-12-31T09:35:22.911Z DRIVER   added request handler for AddNodeToNetwork (0x4a)...
                                  1 registered
2021-12-31T09:35:22.912Z DRIVER   added request handler for RemoveNodeFromNetwork (0x4b)...
                                  1 registered
2021-12-31T09:35:22.913Z DRIVER   added request handler for ReplaceFailedNode (0x63)...
                                  1 registered
2021-12-31T09:35:22.914Z CNTRLR   querying controller IDs...
2021-12-31T09:35:22.939Z SERIAL » 0x01030020dc                                                         (5 bytes)
2021-12-31T09:35:22.941Z DRIVER » [REQ] [GetControllerId]
2021-12-31T09:35:22.949Z SERIAL « [ACK]                                                                   (0x06)
2021-12-31T09:35:22.955Z SERIAL « 0x01080120f422a77a01dc                                              (10 bytes)
2021-12-31T09:35:22.957Z SERIAL » [ACK]                                                                   (0x06)
2021-12-31T09:35:22.959Z DRIVER « [RES] [GetControllerId]
                                    payload: 0xf422a77a01
2021-12-31T09:35:22.983Z CNTRLR   received controller IDs:
                                    home ID:     0xf422a77a
                                    own node ID: 1
2021-12-31T09:35:22.983Z CNTRLR   querying API capabilities...
2021-12-31T09:35:23.011Z SERIAL » 0x01030007fb                                                         (5 bytes)
```

System is then properly initialised but then subsequent commands fail the same way, e.g. when starting inclusion:
```
2021-12-31T09:44:48.427Z CNTRLR   Starting inclusion process with strategy Default...
2021-12-31T09:44:48.479Z SERIAL » 0x0105004ac10372                                                     (7 bytes)
2021-12-31T09:44:48.481Z DRIVER » [REQ] [AddNodeToNetwork]
                                    payload: 0xc103
2021-12-31T09:44:49.496Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2021-12-31T09:44:49.599Z SERIAL » 0x0105004ac10372                                                     (7 bytes)
2021-12-31T09:44:49.603Z DRIVER » [REQ] [AddNodeToNetwork]
                                    payload: 0xc103
2021-12-31T09:44:50.618Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2021-12-31T09:44:51.723Z SERIAL » 0x0105004ac10372                                                     (7 bytes)
2021-12-31T09:44:51.727Z DRIVER » [REQ] [AddNodeToNetwork]
                                    payload: 0xc103
2021-12-31 09:44:52.760 INFO ZWAVE: Timeout while waiting for an ACK from the controller (ZW0200) startInclusion undefined
```

**Comment by jmgiaever** [comment]
Include hardware and version (both Z2M and zwjs).

**Comment by renmarq** [comment]
Hi, I'm running it through docker using 'latest' tag. From checking package.json inside docker image I get the following:
```
Z2M: 6.0.3
zwjs: ^8.8.3
```

I've also been digging a little bit more (and added a bit more log context in first post). It seems each time the two first attempt are linked to 'unknown' (not timeout) errors then the third attempt seems to conclude it's a timeout (which doesn't seem consistent with the code).

The issue I'm facing is on a raspberrypi.

**Comment by renmarq** [comment]
Sorry I closed it by mistake

**Comment by jmgiaever** [comment]
Hi, thanks. Which path are you using for the controller, in your settings? (Both docker and Z2M)

**Comment by renmarq** [comment]
/dev/zwave which is mapped in docker from /dev/serial/by-id/usb-0658_0200-if00

**Comment by renmarq** [comment]
the problem is linked to the driver, not Z2M, should I close this issue and open a new one with zwjs. I've written a simple js script to call the driver directly and I get the same error (although this time I see the error code, which is '100':

```
/mnt/zwave-test # node main.js 
12:09:43.325 DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                      ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                        ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                       ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                      ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                      ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
12:09:43.385 DRIVER   version 8.9.1
12:09:43.387 DRIVER   
12:09:43.388 DRIVER   starting driver...
12:09:43.445 DRIVER   opening serial port /dev/zwavetst
12:09:43.480 DRIVER   serial port opened
12:09:43.484 SERIAL » [NAK]                                                                   (0x15)
12:09:43.496 DRIVER   loading configuration...
12:09:43.533 CONFIG   Using external configuration dir /usr/src/app/store/.config-db
12:09:43.534 CONFIG   version 8.9.1
12:09:46.390 DRIVER   beginning interview...
12:09:46.395 DRIVER   added request handler for AddNodeToNetwork (0x4a)...
                      1 registered
12:09:46.397 DRIVER   added request handler for RemoveNodeFromNetwork (0x4b)...
                      1 registered
12:09:46.399 DRIVER   added request handler for ReplaceFailedNode (0x63)...
                      1 registered
12:09:46.402 CNTRLR   querying controller IDs...
12:09:47.041 SERIAL » 0x01030020dc                                                         (5 bytes)
12:09:47.047 DRIVER » [REQ] [GetControllerId]
12:09:48.088 CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                      n 100 ms.
12:09:48.196 SERIAL » 0x01030020dc                                                         (5 bytes)
12:09:48.201 DRIVER » [REQ] [GetControllerId]
12:09:49.214 CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                      n 1100 ms.
12:09:50.320 SERIAL » 0x01030020dc                                                         (5 bytes)
12:09:50.324 DRIVER » [REQ] [GetControllerId]
12:09:51.377 DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK 
                      from the controller (ZW0200)
                          at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/D
                      river.ts:3350:23)
                          at ZWaveController.identify (/usr/src/app/node_modules/zwave-js/src/lib/co
                      ntroller/Controller.ts:677:33)
                          at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js
                      /src/lib/driver/Driver.ts:977:26)
                          at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/drive
                      r/Driver.ts:857:16)
ZWaveError: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:3350:23)
    at ZWaveController.identify (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:677:33)
    at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:977:26)
    at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:857:16) (ZW0100)
    at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:874:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 100,
  context: undefined,
  transactionSource: undefined
}
12:09:51.411 DRIVER   destroying driver instance...
12:09:51.418 DRIVER   driver instance destroyed
```

**Comment by jmgiaever** [comment]
I think @robertsLando  can move it within the organization. But he maybe knows if there's something you'd have to do with your docker to fix it. I guess the problem is docker and mapping of the device.

**Comment by renmarq** [comment]
I just ran my test script outside of docker, directly from Raspbian and I still have the same issue. So it's not linked to docker.

**Comment by jmgiaever** [comment]
So your script can't use the device either?

**Comment by renmarq** [comment]
No, same issue. But it's not 100% of the time. Sometimes it works but rarely.

**Comment by jmgiaever** [comment]
I guess you're in the wrong forum then; you should ask for help in a forum for the Raspbian OS.

**Comment by renmarq** [comment]
It's a protocol issue, I don't think OS forum will help. I've got the feeling it's linked to raspberry processing speed and the driver not waiting long enough, or maybe timing issue with the USB port. As you can see from the logs the serial port is open so it's not a privilege or access issue:
```
12:09:43.445 DRIVER   opening serial port /dev/zwavetst
12:09:43.480 DRIVER   serial port opened
```
I'm now trying to to call Driver.sendMessage directly to try to get more information but I'm struggling to instantiate the right objects.

**Comment by jmgiaever** [comment]
@AlCalzone

**Comment by renmarq** [comment]
I made some progress. I coded a test calling directly node-serialport and this way I always get an answer from the controller. So the issue lies somewhere in the driver:
```
(homeassistant) homeassistant@raspberrypi:~/zwave-test $ node serial.js 
1 bytes written (0x 15 )
5 bytes written (0x 01030020dc )
Data: <Buffer 06 01 08 01 20 f4 22 a7 7a 01 dc>
Data: <Buffer 01 08 01 20 f4 22 a7 7a 01 dc>
Data: <Buffer 01 08 01 20 f4 22 a7 7a 01 dc>
Data: <Buffer 01 08 01 20 f4 22 a7 7a 01 dc>
^C
(homeassistant) homeassistant@raspberrypi:~/zwave-test $ node serial.js 
1 bytes written (0x 15 )
5 bytes written (0x 01030020dc )
Data: <Buffer 06 01 08 01 20 f4 22 a7 7a 01 dc>
Data: <Buffer 01 08 01 20 f4 22 a7 7a 01 dc>
Data: <Buffer 01 08 01 20 f4 22 a7 7a 01 dc>
Data: <Buffer 01 08 01 20 f4 22 a7 7a 01 dc>
^C
(homeassistant) homeassistant@raspberrypi:~/zwave-test $ node serial.js 
1 bytes written (0x 15 )
5 bytes written (0x 01030020dc )
Data: <Buffer 06 01 08 01 20 f4 22 a7 7a 01 dc>
Data: <Buffer 01 08 01 20 f4 22 a7 7a 01 dc>
Data: <Buffer 01 08 01 20>
Data: <Buffer f4 22 a7 7a 01 dc>
Data: <Buffer 01 08 01 20 f4 22 a7 7a 01 dc>
^C
```

**Comment by renmarq** [comment]
I think I'm getting crazy a bit. I've just relaunched zwavejs2mqtt and everything works perfectly now. I'll keep monitoring for a while to see.

**Comment by AlCalzone** [comment]
Some Z-Wave sticks, especially the older ones seem to get stuck somewhat frequently when rebooting or restarting containers. 

Yes, increasing the ACK timeout is possible, but it won't help with that. If you look at the timestamps, the driver is already waiting a full second for something that normally happens within 10ms.

If there is no response from the stick at all after starting, there's either something wrong with the OS or container configuration, or you'll need to re-plug the stick to force it to reboot.

**Comment by robertsLando** [comment]
@AlCalzone maybe disabling soft reset could make it more reliable?

**Comment by AlCalzone** [comment]
If you look at the logs, it didn't even get that far. If this was originally caused by soft-resetting the stick, the driver now knows not to soft-reset it again.

**Comment by renmarq** [comment]
I think it's a combination of the OS + stick state. But re-plug and reboot didn't help as I kept having the issue on the raspberry after having done both. Actually I switch the stick multiple time between the raspberry (which had the issue) and my laptop which had not. And I was able to reproduce the issue outside the container.

I still don't know why it's working now. At least if it happens again I'll be much faster at investigating as I understand much better how the system works. Thank you all for your quick support.

I'll close for now and will re-open if it reoccurs.

**Comment by alertedsnake** [comment]
> I made some progress. I coded a test calling directly node-serialport and this way I always get an answer from the controller. So the issue lies somewhere in the driver:

Can you share the script you're using for this?  I'm having similar issues and trying to debug.

**Comment by renmarq** [comment]
Sure, there you go (just replace serial port address by the one corresponding to your usb dongle which will be listed by the first command):

serial.js:
```
import serialport from "serialport";
import SerialPort from "serialport";
 
// list serial ports:
serialport.list().then (
  ports => ports.forEach(port =>console.log(port.path)),
  err => console.log(err)
)
let port = new SerialPort('/dev/tty.usbmodem14301', 115200);

function writeDataLater(data, delay) {
    setTimeout(() => { writeData(data)}, delay); 
}

function writeData(data) {
    const buf = Buffer.from(data, 'hex');

    port.write(buf, function(err) {
        if (err) {
            return console.log('Error on write: ', err.message)
        }
        console.log(buf.length, 'bytes written (0x', data, ')');
    });
}

port.on('error', function(err) {
    console.log('Error: ', err.message)
})

port.on('data', function (data) {
    console.log('Data:', data)
})

//writeData(0x15);
//writeData(0x08); // Soft reset
writeData('15');
writeData('01030020dc');
//writeDataLater('15', 1000);
//writeDataLater('01030020dc', 2000);
```


package.json:
```
{
  "name": "zwave-test",
  "version": "1.0.0",
  "type": "module",
  "dependencies": {
    "zwave-js": "^8.9.2"
  }
}
```

Let me know if you have questions.

**Comment by alertedsnake** [comment]
Awesome, thanks a bunch!
