### ISSUE TITLE
Schlage lock can receive data but not send - BE469ZP

### ISSUE THREAD

**Issue by mhendu** [zwave-js/zwavejs2mqtt#2126]
I had this deadbolt working on legacy Z-Wave via another PC. It was detected properly on my new PC, and whenever I go to the lock and unlock it the device reports back to the controller, but I cannot push commands to it. If I do so it gives up after three attempts and marks it as dead. Any suggestions?

2021-12-31 14:24:05.116 INFO ZWAVE: Node 28: value updated: 98-0-currentMode 0 => 0
2021-12-31 14:24:05.118 INFO ZWAVE: Node 28: value updated: 98-0-outsideHandlesCanOpenDoor false,false,false,false => false,false,false,false
2021-12-31 14:24:05.119 INFO ZWAVE: Node 28: value updated: 98-0-insideHandlesCanOpenDoor false,false,false,false => false,false,false,false
2021-12-31 14:24:05.121 INFO ZWAVE: Node 28: value updated: 98-0-latchStatus open => open
2021-12-31 14:24:05.122 INFO ZWAVE: Node 28: value updated: 98-0-boltStatus locked => unlocked
2021-12-31 14:24:05.123 INFO ZWAVE: Node 28: value updated: 98-0-doorStatus open => open
2021-12-31 14:24:07.843 INFO ZWAVE: Node 28: value updated: 98-0-currentMode 0 => 255
2021-12-31 14:24:07.851 INFO ZWAVE: Node 28 CC Notification {
  type: 6,
  event: 5,
  label: 'Access Control',
  eventLabel: 'Keypad lock operation',
  parameters: undefined
}

2021-12-31T20:28:29.912Z CNTRLR   [Node 028] The node did not respond after 3 attempts, it is presumed dead
2021-12-31 14:28:29.915 INFO ZWAVE: Node 28 is now dead
2021-12-31T20:28:29.916Z CNTRLR   [Node 028] The node is now dead.
2021-12-31 14:28:30.455 ERROR ZWAVE-SERVER: Failed to send the command after 1 attempts (Status NoAck) (ZW0204)
ZWaveError: Failed to send the command after 1 attempts (Status NoAck) (ZW0204)
    at Driver.sendMessage (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:3350:23)
    at Driver.sendCommand (/opt/node_modules/zwave-js/src/lib/driver/Driver.ts:3526:28)
    at DoorLockCCAPI.set (/opt/node_modules/zwave-js/src/lib/commandclass/DoorLockCC.ts:292:21)
    at Proxy.DoorLockCCAPI.<computed> (/opt/node_modules/zwave-js/src/lib/commandclass/DoorLockCC.ts:140:15)
    at ZWaveNode.setValue (/opt/node_modules/zwave-js/src/lib/node/Node.ts:851:14)
    at Function.handle (/opt/node_modules/@zwave-js/server/dist/lib/node/message_handler.js:20:44)
    at Object.node (/opt/node_modules/@zwave-js/server/dist/lib/server.js:39:91)
    at Client.receiveMessage (/opt/node_modules/@zwave-js/server/dist/lib/server.js:95:99)
    at WebSocket.<anonymous> (/opt/node_modules/@zwave-js/server/dist/lib/server.js:48:45)
    at WebSocket.emit (node:events:390:28)

**Comment by jmgiaever** [comment]
Include driver logs. You'll find them under z-wave in settings.

**Comment by mhendu** [comment]
OK, thanks. Attached.
[zwavejs2mqtt_2021-12-31.log](https://github.com/zwave-js/zwavejs2mqtt/files/7797026/zwavejs2mqtt_2021-12-31.log)
[zwavejs_2021-12-31.log](https://github.com/zwave-js/zwavejs2mqtt/files/7797027/zwavejs_2021-12-31.log)

**Comment by mhendu** [comment]
OK, not really sure how this happened, but it wasn't letting me remove a couple of dead nodes. I unplugged the Z-stick while the service was running so I could exclude another device, then plugged it back in and restarted the service, then tried to remove the dead nodes and it now let me remove them. Also, now the lock works. Presumably this is related somehow but a little unclear to me.
