### ISSUE TITLE
[bug] Uncaught exception: TypeError: Cannot read property 'getCCVersion' of undefined

### ISSUE THREAD

**Issue by parityhero** [zwave-js/zwavejs2mqtt#2162]
Hi,

One of my nodes went dead and the docker container closed, and now everytime I try to start it, it begins to load then exits again.

Full log is available here: https://pastebin.com/kqW3Hug7

Below is an excerpt of what I believe may be causing the issue: 

```
[90m2022-01-10 18:17:12.242[39m [31mERROR[39m [1mZWAVE[22m: Interview of node 47 has failed: Attempt 1/5 failed
[90m2022-01-10 18:17:12.496[39m [32mINFO[39m [1mZWAVE[22m: Node 47 is now dead
[90m2022-01-10 18:17:12.498[39m [32mINFO[39m [1mZWAVE[22m: Controller status: Scan completed
[90m2022-01-10 18:17:12.500[39m [32mINFO[39m [1mZWAVE[22m: Network scan complete. Found: 35 nodes
[90m2022-01-10 18:17:29.170[39m [31mERROR[39m [1mZWAVE[22m: Interview of node 47 has failed: The node is dead
[90m2022-01-10 18:17:37.429[39m [32mINFO[39m [1mZWAVE[22m: Node 47: has returned from the dead
[90m2022-01-10 18:17:50.426[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value updated: 134-0-libraryType 3 => 3
[90m2022-01-10 18:17:50.429[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value updated: 134-0-protocolVersion 7.13 => 7.13
[90m2022-01-10 18:17:50.431[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value updated: 134-0-firmwareVersions 10.0 => 10.0
[90m2022-01-10 18:17:50.433[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value updated: 134-0-hardwareVersion 1 => 1
[90m2022-01-10 18:17:53.552[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 134-0-sdkVersion => 7.13.9
[90m2022-01-10 18:17:53.556[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 134-0-applicationFrameworkAPIVersion => 10.13.9
[90m2022-01-10 18:17:53.559[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 134-0-applicationFrameworkBuildNumber => 405
[90m2022-01-10 18:17:53.560[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 134-0-hostInterfaceVersion => unused
[90m2022-01-10 18:17:53.566[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 134-0-hostInterfaceBuildNumber => 0
[90m2022-01-10 18:17:53.568[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 134-0-zWaveProtocolVersion => 7.13.9
[90m2022-01-10 18:17:53.571[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 134-0-zWaveProtocolBuildNumber => 405
[90m2022-01-10 18:17:53.572[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 134-0-applicationVersion => 10.0.1
[90m2022-01-10 18:17:53.573[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 134-0-applicationBuildNumber => 43707
[90m2022-01-10 18:17:54.489[39m [32mINFO[39m [1mZWAVE[22m: Node 47: metadata updated: 135-0-80-3
[90m2022-01-10 18:17:54.490[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 135-0-80-3 => 0
[90m2022-01-10 18:17:54.491[39m [32mINFO[39m [1mZWAVE[22m: Node 47: metadata updated: 135-0-80-4
[90m2022-01-10 18:17:54.492[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 135-0-80-4 => 0
[90m2022-01-10 18:17:54.493[39m [32mINFO[39m [1mZWAVE[22m: Node 47: metadata updated: 135-0-80-5
[90m2022-01-10 18:17:54.494[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 135-0-80-5 => 0
[90m2022-01-10 18:18:00.056[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 38-0-targetValue => undefined
[90m2022-01-10 18:18:00.060[39m [32mINFO[39m [1mZWAVE[22m: Node 47: metadata updated: 38-0-Up
[90m2022-01-10 18:18:00.063[39m [32mINFO[39m [1mZWAVE[22m: Node 47: metadata updated: 38-0-Down
[90m2022-01-10 18:18:00.277[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added 47-38-0-targetValue => 0
[90m2022-01-10 18:18:00.277[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value updated: 38-0-targetValue undefined => 0
[90m2022-01-10 18:18:00.279[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added: 38-0-duration => 0s
[90m2022-01-10 18:18:00.294[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value added 47-38-0-currentValue => 0
[90m2022-01-10 18:18:00.295[39m [32mINFO[39m [1mZWAVE[22m: Node 47: value updated: 38-0-currentValue 0 => 0
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'getCCVersion' of undefined
    at ZwaveClient._updateValueMetadata (/usr/src/app/server/lib/ZwaveClient.js:2346:17)
    at ZwaveClient._parseValue (/usr/src/app/server/lib/ZwaveClient.js:2419:30)
    at ZwaveClient._onNodeMetadataUpdated (/usr/src/app/server/lib/ZwaveClient.js:2096:30)
    at ZWaveNode.emit (node:events:406:35)
    at ZWaveNode.emit (node:domain:470:12)
    at ZWaveNode.translateValueEvent (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:397:8)
    at ValueDB.emit (node:events:394:28)
    at ValueDB.emit (node:domain:470:12)
    at ValueDB.setMetadata (/usr/src/app/node_modules/@zwave-js/core/src/values/ValueDB.ts:414:9)
    at ConfigurationCC.extendParamInformation (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/ConfigurationCC.ts:1168:11)
```

**Comment by elad-bar** [comment]
also here
```
today at 11:10:46 PM23:10:46.585 DRIVER   Node 14, Endpoint undefined: Trying to access endpoint instance before Multi C
today at 11:10:46 PM                      hannel interview
today at 11:10:46 PMThis error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
today at 11:10:46 PMTypeError: Cannot read property 'getCCVersion' of undefined
today at 11:10:46 PM    at ZwaveClient._updateValueMetadata (/usr/src/app/server/lib/ZwaveClient.js:2346:17)
today at 11:10:46 PM    at ZwaveClient._parseValue (/usr/src/app/server/lib/ZwaveClient.js:2419:30)
today at 11:10:46 PM    at ZwaveClient._onNodeMetadataUpdated (/usr/src/app/server/lib/ZwaveClient.js:2096:30)
today at 11:10:46 PM    at ZWaveNode.emit (node:events:406:35)
today at 11:10:46 PM    at ZWaveNode.emit (node:domain:470:12)
today at 11:10:46 PM    at ZWaveNode.translateValueEvent (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:397:8)
today at 11:10:46 PM    at ValueDB.emit (node:events:394:28)
today at 11:10:46 PM    at ValueDB.emit (node:domain:470:12)
today at 11:10:46 PM    at ValueDB.setMetadata (/usr/src/app/node_modules/@zwave-js/core/src/values/ValueDB.ts:414:9)
today at 11:10:46 PM    at ConfigurationCC.extendParamInformation (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/ConfigurationCC.ts:1168:11)
today at 11:10:46 PMContainer stopped
```

**Comment by creeg2** [comment]
I'm experiencing the same error.  This is a brand new docker instance using an existing zwave stick (Aeon Labs) with existing nodes attached to the network.

```
zwavejs2mqtt    | 2022-01-11 01:13:00.750 INFO ZWAVE: Node 7 is alive
zwavejs2mqtt    | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zwavejs2mqtt    | TypeError: Cannot read property 'getCCVersion' of undefined
zwavejs2mqtt    |     at ZwaveClient._updateValueMetadata (/usr/src/app/server/lib/ZwaveClient.js:2346:17)
zwavejs2mqtt    |     at ZwaveClient._parseValue (/usr/src/app/server/lib/ZwaveClient.js:2419:30)
zwavejs2mqtt    |     at ZwaveClient._onNodeMetadataUpdated (/usr/src/app/server/lib/ZwaveClient.js:2096:30)
zwavejs2mqtt    |     at ZWaveNode.emit (node:events:394:28)
zwavejs2mqtt    |     at ZWaveNode.emit (node:domain:470:12)
zwavejs2mqtt    |     at ZWaveNode.translateValueEvent (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:397:8)
zwavejs2mqtt    |     at ValueDB.emit (node:events:394:28)
zwavejs2mqtt    |     at ValueDB.emit (node:domain:470:12)
zwavejs2mqtt    |     at ValueDB.setMetadata (/usr/src/app/node_modules/@zwave-js/core/src/values/ValueDB.ts:414:9)
zwavejs2mqtt    |     at ConfigurationCC.extendParamInformation (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/ConfigurationCC.ts:1168:11)
```

**Comment by Botched1** [comment]
I'm also getting various errors on the new release, too:"

```
2022-01-11T01:26:35.077Z CNTRLR [Node 117] Timed out while waiting for a response from the node (ZW0201)
2022-01-11T01:26:35.078Z CNTRLR [Node 117] Querying securely supported commands (S0) timed out
2022-01-11T01:26:35.111Z CNTRLR [Node 117] Embedded device config loaded
2022-01-11T01:26:35.114Z CNTRLR [Node 117] Interviewing User Code...
2022-01-11T01:26:35.114Z CNTRLR » [Node 117] querying capabilities...
2022-01-11T01:26:36.655Z CNTRLR » [Node 117] querying number of user codes...
2022-01-11T01:26:36.918Z CNTRLR [Node 117] Interviewing Configuration...
2022-01-11T01:26:36.918Z CNTRLR [Node 117] ConfigurationCC: Loading configuration parameters from device confi
g
2022-01-11T01:26:36.920Z DRIVER Node 117, Endpoint undefined: Trying to access endpoint instance before Multi
Channel interview
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'getCCVersion' of undefined
at ZwaveClient._updateValueMetadata (/usr/src/app/server/lib/ZwaveClient.js:2346:17)
at ZwaveClient._parseValue (/usr/src/app/server/lib/ZwaveClient.js:2419:30)
at ZwaveClient._onNodeMetadataUpdated (/usr/src/app/server/lib/ZwaveClient.js:2096:30)
at ZWaveNode.emit (node:events:406:35)
at ZWaveNode.emit (node:domain:470:12)
at ZWaveNode.translateValueEvent (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:397:8)
at ValueDB.emit (node:events:394:28)
at ValueDB.emit (node:domain:470:12)
at ValueDB.setMetadata (/usr/src/app/node_modules/@zwave-js/core/src/values/ValueDB.ts:414:9)
at ConfigurationCC.extendParamInformation (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/ConfigurationCC.ts:1168:11)
2022-01-11T01:26:40.230Z CNTRLR Re-opening serial port...
```

**Comment by krobertson** [comment]
I'm experiencing this too on a fresh instance I was migrating nodes over to. My existing machines was running 6.2.0 while the new one was on 6.3.0. I rolled back to 6.2.0 and it seems to be ok so far.

**Comment by Botched1** [comment]
> I rolled back to 6.2.0 and it seems to be ok so far.

Ditto. Had to roll back, but everything is working after I rolled back. So I'll wait and see what the devs say.

**Comment by skythedesu** [comment]
+1, rolling back to zwavejs/zwavejs2mqtt:6.2.0 from zwavejs/zwavejs2mqtt:latest instantly resolved the issue for me. Everything was stuck on ProtocolInfo. (Well, instantly, other than battery devices needing to be woken up.) Really freaked me out for a hot minute there.

**Comment by AlCalzone** [comment]
@robertsLando
```
TypeError: Cannot read property 'getCCVersion' of undefined
```

The CC versions for endpoints can only be accessed **AFTER** the interview.

**Comment by robertsLando** [comment]
Patch coming
