### ISSUE TITLE
[question] Start up crash on previously stable docker - Endpoint undefined: Trying to access endpoint instance before Multi Channel interview

### ISSUE THREAD

**Issue by clinoid** [zwave-js/zwavejs2mqtt#2172]
I am having an error on startup for the zwavejs2mqtt docker container which previously had run very well. The issue seems to have started after I requested to reinterview an Ecolink Tilt garage door sensor (node 85). This eventually resulted in an unexpected crash and now I see the following log error and startup crash every time I start the docker. I have rebooted the system. The zwave stick is a HUBZB-1. 

Any recommendations on how to fix this? I guess I can restore from an image from a few days ago if I need to, but wanted to see if there might be another solution.

The Log from the debug window [ relevant portion]

2022-01-11T11:52:06.157Z CNTRLR [Node 085] Interviewing Configuration...
2022-01-11T11:52:06.157Z CNTRLR [Node 085] ConfigurationCC: Loading configuration parameters from device confi
g
2022-01-11T11:52:06.159Z DRIVER Node 85, Endpoint undefined: Trying to access endpoint instance before Multi C
hannel interview
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'getCCVersion' of undefined
at ZwaveClient._updateValueMetadata (/usr/src/app/server/lib/ZwaveClient.js:2346:17)
at ZwaveClient._parseValue (/usr/src/app/server/lib/ZwaveClient.js:2419:30)
at ZwaveClient._onNodeMetadataUpdated (/usr/src/app/server/lib/ZwaveClient.js:2096:30)
at ZWaveNode.emit (node:events:394:28)
at ZWaveNode.emit (node:domain:470:12)
at ZWaveNode.translateValueEvent (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:397:8)
at ValueDB.emit (node:events:394:28)
at ValueDB.emit (node:domain:470:12)
at ValueDB.setMetadata (/usr/src/app/node_modules/@zwave-js/core/src/values/ValueDB.ts:414:9)
at ConfigurationCC.extendParamInformation (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/ConfigurationCC.ts:1168:11)

**Comment by robertsLando** [comment]
Fixed in 6.3.1
