### ISSUE TITLE
[Bug]: zwavejs2mqtt crash and restart

### ISSUE THREAD

**Issue by Minims** [zwave-js/zwavejs2mqtt#2201]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.4.1

### ZwaveJS version

8.11.1

### Describe the bug

The application is crashing : 
In that case Node 3 is : Eurotronics | Thermostatic Valve | Spirit

```
2022-01-21T10:17:51.908Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2022-01-21T10:17:53.439Z CNTRLR « [Node 003] received supported notification types:
                                  · Power Management
                                  · System
2022-01-21T10:17:53.440Z CNTRLR » [Node 003] querying supported notification events for Power Management...
2022-01-21 11:17:53.527 INFO ZWAVE: Node 3: metadata updated: 113-0-Power Management-Battery maintenance status
2022-01-21T10:17:53.534Z CNTRLR « [Node 003] received supported notification events for Power Management: 10, 11
2022-01-21T10:17:53.535Z CNTRLR » [Node 003] querying supported notification events for System...
2022-01-21 11:17:53.627 INFO ZWAVE: Node 3: metadata updated: 113-0-System-Hardware status
2022-01-21T10:17:53.637Z CNTRLR « [Node 003] received supported notification events for System: 3
2022-01-21T10:17:53.638Z CNTRLR » [Node 003] enabling notifications for Power Management...
2022-01-21 11:17:53.703 INFO ZWAVE: Node 3: value added: 113-0-Power Management-Battery maintenance status => 0
2022-01-21T10:17:53.705Z CNTRLR » [Node 003] enabling notifications for System...
2022-01-21 11:17:53.814 INFO ZWAVE: Node 3: value added: 113-0-System-Hardware status => 0
2022-01-21 11:17:53.861 INFO ZWAVE: Node 3: interview stage COMMANDCLASSES completed
2022-01-21T10:17:53.864Z CNTRLR   [Node 003] Interview stage completed: CommandClasses
2022-01-21 11:17:53.866 INFO ZWAVE: Node 3: interview stage OVERWRITECONFIG completed
2022-01-21T10:17:53.877Z CNTRLR   [Node 003] Interview stage completed: OverwriteConfig
2022-01-21 11:17:53.877 INFO ZWAVE: Node 3: interview stage COMPLETE completed
2022-01-21T10:17:53.888Z CNTRLR   [Node 003] Interview completed
2022-01-21 11:17:53.920 INFO ZWAVE: Node 3: value added 3-38-0-targetValue => undefined
2022-01-21 11:17:53.923 INFO ZWAVE: Node 3: value added 3-38-0-duration => NaNs
2022-01-21 11:17:53.961 INFO ZWAVE: Node 3: value added 3-38-0-currentValue => 89
2022-01-21 11:17:53.963 INFO ZWAVE: Node 3: value added 3-38-0-Up => undefined
2022-01-21 11:17:53.966 INFO ZWAVE: Node 3: value added 3-38-0-Down => undefined
2022-01-21 11:17:53.968 INFO ZWAVE: Node 3: value added 3-49-0-Air temperature => 15.65
2022-01-21 11:17:53.970 INFO ZWAVE: Node 3: value added 3-64-0-mode => 1
2022-01-21 11:17:53.972 INFO ZWAVE: Node 3: value added 3-64-0-manufacturerData => undefined
2022-01-21 11:17:53.974 INFO ZWAVE: Node 3: value added 3-67-0-setpoint-1 => 20
2022-01-21 11:17:53.975 INFO ZWAVE: Node 3: value added 3-67-0-setpoint-11 => 18
2022-01-21 11:17:53.977 INFO ZWAVE: Node 3: value added 3-112-0-1 => 0
2022-01-21 11:17:53.979 INFO ZWAVE: Node 3: value added 3-112-0-2 => 0
2022-01-21 11:17:53.982 INFO ZWAVE: Node 3: value added 3-112-0-3 => 1
2022-01-21 11:17:53.983 INFO ZWAVE: Node 3: value added 3-112-0-4 => 1
2022-01-21 11:17:53.985 INFO ZWAVE: Node 3: value added 3-112-0-5 => 1
2022-01-21 11:17:53.987 INFO ZWAVE: Node 3: value added 3-112-0-6 => 0
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
SyntaxError: Octal literals are not allowed in strict mode.
    at Gateway._onValueChanged (/opt/server/lib/Gateway.js:1333:45)
    at ZwaveClient.emit (node:events:390:28)
    at ZwaveClient.emit (node:domain:475:12)
    at ZwaveClient.emitValueChanged (/opt/server/lib/ZwaveClient.js:780:14)
    at ZwaveClient._addValue (/opt/server/lib/ZwaveClient.js:2461:22)
    at ZwaveClient._onNodeReady (/opt/server/lib/ZwaveClient.js:1964:18)
    at ZWaveNode.emit (node:events:402:35)
    at ZWaveNode.emit (node:domain:475:12)
    at ZWaveNode.onReadyChange (/opt/node_modules/zwave-js/src/lib/node/Node.ts:496:19)
    at /opt/node_modules/zwave-js/src/lib/node/Node.ts:266:10
[11:17:54] INFO: Starting the Z-Wave JS to MQTT...
```

### To Reproduce

Reinterview node.

### Expected behavior

Application does not crash

**Comment by Minims** [comment]
Rolling back to those version make it works again : 
zwavejs : 8.10.2
zwavejs2mqtt : 6.3.1

**Comment by robertsLando** [comment]
What are you sending via mqtt?

**Comment by robertsLando** [comment]
Could you set logger level to debug please and send me the log file?

**Comment by Minims** [comment]
Here is the addon logs in HA interface : 

```
2022-01-21 17:17:28.155 INFO ZWAVE: Node 3: value added 3-112-0-1 => 0
2022-01-21 17:17:28.157 INFO ZWAVE: Node 3: value added 3-112-0-2 => 0
2022-01-21 17:17:28.158 INFO ZWAVE: Node 3: value added 3-112-0-3 => 1
2022-01-21 17:17:28.159 INFO ZWAVE: Node 3: value added 3-112-0-4 => 1
2022-01-21 17:17:28.160 INFO ZWAVE: Node 3: value added 3-112-0-5 => 1
2022-01-21 17:17:28.161 INFO ZWAVE: Node 3: value added 3-112-0-6 => 0
2022-01-21 17:17:28.162 INFO ZWAVE: Node 3: value added 3-112-0-7 => 0
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
SyntaxError: Octal literals are not allowed in strict mode.
    at Gateway._onValueChanged (/opt/server/lib/Gateway.js:1333:45)
    at ZwaveClient.emit (node:events:390:28)
    at ZwaveClient.emit (node:domain:475:12)
    at ZwaveClient.emitValueChanged (/opt/server/lib/ZwaveClient.js:780:14)
    at ZwaveClient._addValue (/opt/server/lib/ZwaveClient.js:2461:22)
    at ZwaveClient._onNodeReady (/opt/server/lib/ZwaveClient.js:1964:18)
    at ZWaveNode.emit (node:events:402:35)
    at ZWaveNode.emit (node:domain:475:12)
    at ZWaveNode.onReadyChange (/opt/node_modules/zwave-js/src/lib/node/Node.ts:496:19)
    at /opt/node_modules/zwave-js/src/lib/node/Node.ts:266:10
```

and the logs from zwavejs2mqtt : 
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7915165/zwavejs2mqtt-store.zip)


My MQTT conf : 
![zwavejs](https://user-images.githubusercontent.com/1724785/150562466-25ab5c40-9f2b-4031-8cbd-867b0bcbf934.png)

**Comment by robertsLando** [comment]
@Minims I don't see that error logged in zwavejs2mqtt logs you sent, could you show me general section settings? Is log level set to debug?

**Comment by Minims** [comment]
I don't see it too, seems it is only visible in HA.
Yes I have setup it to debug and save.

![Capture d’écran 2022-01-21 à 17 59 24](https://user-images.githubusercontent.com/1724785/150568551-48ea5ae4-2cf8-4abf-a76e-5fbb85bd574a.png)

**Comment by Minims** [comment]
Retry with debug in HA add-on config AND zwave2mqtt config
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7915435/zwavejs2mqtt-store.zip)
![Capture d’écran 2022-01-21 à 18 05 09](https://user-images.githubusercontent.com/1724785/150569622-2b23008f-9ffb-4f11-9ec5-2979d737bbe9.png)

**Comment by kpine** [comment]
What are you trying to do exactly?

According to the docs, "Post Operation" is supposed to be a mathematical expression. https://zwave-js.github.io/zwavejs2mqtt/#/usage/setup?id=device-values-configuration

> Post operation: If you want to convert your value (valid examples: '/10' '/100' '*10' '*100')

So the purpose is to transform a Z-Wave number value using a mathematical expression.

The way the z2m code is written, your post operations are creating numbers by concatenation, not by any kind of mathematical operation. The exception is being thrown because JavaScript strict mode doesn't let you use octal literals, and the last config value `3-112-0-7` is `0`. Your post operations is only `"30"`, so that results in the concatenated string `"030"`, which is an octal number when evaluated as JavaScript.

Essentially, this is what's happening:
```
❯ node --use-strict
Welcome to Node.js v16.13.2.
Type ".help" for more information.
> eval("0" + "30")
Uncaught SyntaxError: Octal literals are not allowed in strict mode.
>
```

You probably only see the error for this value because it is zero, since prepending 0 to another number makes it an octal in Javascript.

(Perhaps the function `_isValidOperation` is checking the post operation correctly, allowing numbers at the beginning instead of requiring a symbol?)

If you wanted to add 30 to the value, the post operation would be `+30`.

```
> eval("0" + "+30")
30
```

But you have some Post Operation values of `false`, which doesn't make sense.

**Comment by Minims** [comment]
Ok, so I think I misunderstood the device configuration part.

All I want is to set a default configuration for a device type.
For example, I want the `Wake Up` configuration for `Devolo Thermostat` to be always be to `300`

I was thinking this part will check the device value and update it if not correct on each poll interval.

**Comment by kpine** [comment]
> All I want is to set a default configuration for a device type.

There's currently no such functionality.

**Comment by Minims** [comment]
Ok sorry for the opened issue in that case. 

Maybe input can be checked before saving.

But can you tell me in few words what this configuration is supposed to do in that case ? Do you a case as an example ?

Many thanks

**Comment by robertsLando** [comment]
> All I want is to set a default configuration for a device type.

All you can do for that is to use a driver function

**Comment by Minims** [comment]
Many thanks @robertsLando ! this will help my configuration.
