### ISSUE TITLE
[feat] Better zwave-js logging options

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwavejs2mqtt#23]
Is there a way to speficy the location of the log file? @AlCalzone

**Comment by AlCalzone** [comment]
Nope, added it to this list:
https://github.com/zwave-js/node-zwave-js/issues/1062

**Comment by AlCalzone** [comment]
for reference: this will be supported in zwave-js@6.0.0:
https://github.com/zwave-js/node-zwave-js/pull/1167

**Comment by billiaz** [comment]
We also have no way to get driver logs on Console (when docker is involved) it would be nice to be able to see the driver logs there @robertsLando

**Comment by robertsLando** [comment]
Hummm really? Does this also happen with z2m logs? Because yesterday we switched to winston logger... could you give it a try with docker? It's on master

**Comment by billiaz** [comment]
I will give it a try, I suspect I have already this.

**Comment by billiaz** [comment]
@robertsLando the change does not show in console the driver logs when run on docker. The only way to debug driver logs is through store to file.

**Comment by robertsLando** [comment]
@billiaz my question was not if that change fixed the zwavejs side but it may broke also z2m logs as we have moved to winston too and that may be the root cause of the problem. If you still see z2m logs in docker logs it's ok, the problem is something on zwavejs side or maybe it's something related to some env vars wrongly set?

**Comment by jcam** [comment]
@robertsLando the way that loadMeters in lib/Constants.ts accesses config no longer works. Will likely need to be refactored to query the ConfigManager from the zwave-js driver.

In https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/Constants.js there is a reference:
const { lookupMeterScale, lookupMeter } = require('@zwave-js/config')

TypeError: lookupMeter is not a function
at Object.meterType (/usr/src/app/lib/Constants.js:21:19)
at Gateway.discoverValue (/usr/src/app/lib/Gateway.js:1598:32)
at Gateway.onNodeStatus (/usr/src/app/lib/Gateway.js:364:12)
at ZwaveClient.emit (events.js:314:20)
at ZwaveClient.EventEmitter.emit (domain.js:483:12)
at ZwaveClient.onNodeStatus (/usr/src/app/lib/ZwaveClient.js:246:10)
at ZwaveClient.onNodeReady (/usr/src/app/lib/ZwaveClient.js:274:16)
at ZWaveNode.emit (events.js:326:22)
at ZWaveNode.EventEmitter.emit (domain.js:483:12)
at ZWaveNode.onReadyChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:440:19)
at /usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:226:10
at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js:255:17)
at /usr/src/app/node_modules/xstate/lib/interpreter.js:125:23
at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:60:13)
at Scheduler.schedule (/usr/src/app/node_modules/xstate/lib/scheduler.js:44:14)
at Proxy.Interpreter.send (/usr/src/app/node_modules/xstate/lib/interpreter.js:121:29)

Temporary workaround in here avoids the error, but means instantiating an extra copy of ConfigManager:
https://github.com/jcam/zwavejs2mqtt/commit/997f8b8c14ea4704315effba0588c7fed9046a44

**Comment by robertsLando** [comment]
@AlCalzone how can I access the config manager? Could you give me a snippet?

**Comment by jcam** [comment]
^^ resolved this lookupMeter error here: https://github.com/zwave-js/zwavejs2mqtt/pull/183

**Comment by robertsLando** [comment]
Thanks @jcam !
