### ISSUE TITLE
[Bug]: sendCommand can't invoke APIs that take Buffer arguments

### ISSUE THREAD

**Issue by j9brown** [zwave-js/zwavejs2mqtt#2303]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.5.2

### ZwaveJS version

8.11.6

### Describe the bug

The MQTT based `sendCommand` API does not work for commands that take buffers as arguments.
I encountered this issue while attempting to invoke the `sendData` method of the `ManufacturerProprietaryCC` class.

### To Reproduce

Send an MQTT message to the `sendCommand` topic to invoke the `sendData` method of `ManufacturerProprietaryCC`.

Topic: `zwavejs/_CLIENTS/ZWAVE_GATEWAY-HomeAssistant/api/sendCommand/set`.
Message: `{ "nodeId": nodeId, "endpoint": 0, "commandClass": 0x91 }, "sendData", [ 0x001D, [ 0x0D, 0x01, 255, bits ] ]`

This results in the following exception because the second argument is expected to be a `Buffer` but it is instead passed as an Array since the message is being serialized to JSON for transmission via MQTT.

> 2022-03-06 22:27:29.017 INFO ZWAVE: Message dropped because of an unexpected error: The "list[1]" argument must be an instance of Buffer or Uint8Array. Received an instance of Array (ZW0202) sendCommand undefined
2022-03-06 22:27:29.029 INFO MQTT: Message received on zwavejs/_CLIENTS/ZWAVE_GATEWAY-HomeAssistant/api/sendCommand: '{"success":false,"message":"Message dropped because of an unexpected error: The \\"list[1]\\" argument must be an instance of Buffer or Uint8Array. Received an instance of Array (ZW0202)","args":[{"nodeId":57,"endpoint":0,"commandClass":145},"sendData",[29,[13,1,255,3]]],"origin":{"args":[{"nodeId":57,"endpoint":0,"commandClass":145},"sendData",[29,[13,1,255,3]]]}}'
2022-03-06 22:27:29.095 INFO ZWAVE: Success zwave api call driverFunction undefined
2022-03-07T06:27:29.100Z DRIVER Unexpected error during SerialAPI command: TypeError: The "list[1]" argument m
ust be an instance of Buffer or Uint8Array. Received an instance of Array
at new NodeError (node:internal/errors:371:5)
at Function.concat (node:buffer:559:13)
at ManufacturerProprietaryCC.serialize (/opt/node_modules/zwave-js/src/lib
/commandclass/ManufacturerProprietaryCC.ts:207:25)
at SendDataRequest.serialize (/opt/node_modules/zwave-js/src/lib/controlle
r/SendDataMessages.ts:107:37)
at getSerialAPICommandMachineConfig (/opt/node_modules/zwave-js/src/lib/dr
iver/SerialAPICommandMachine.ts:147:18)
at createSerialAPICommandMachine (/opt/node_modules/zwave-js/src/lib/drive
r/SerialAPICommandMachine.ts:385:3)
at executeSerialAPICommand (/opt/node_modules/zwave-js/src/lib/driver/Comm
andQueueMachine.ts:340:43)
at Interpreter.exec (/opt/node_modules/xstate/lib/interpreter.js:852:61)
at Interpreter.execute (/opt/node_modules/xstate/lib/interpreter.js:204:14
)
at Interpreter.update (/opt/node_modules/xstate/lib/interpreter.js:230:12)

Note the signature of `sendData` expects a `Buffer`: https://github.com/zwave-js/node-zwave-js/blob/67e716a2fcf6477f10afb96fec8978cae91f990e/packages/zwave-js/src/lib/commandclass/ManufacturerProprietaryCC.ts#L37

### Expected behavior

The call should not crash.  Either because the needed `Buffer` is deserialized by zwave2mqtt prior to invoking the method or because the method (and perhaps others like it) is made to be tolerant of arrays.

### Additional context

I was able to work around the issue locally by using the `driverFunction` API to send a function to invoke `sendData` with a `Buffer` but it's kinda hacky:

> const func =
    "const nodeId = " + String(nodeId) + ";" +
    "const bits = " + String(bits) + ";" +
    "const node = driver.controller.nodes.get(nodeId);" +
    "const endpoint = node.getEndpoint(0);" +
    "const api = endpoint.commandClasses[0x91];" +
    "await api.sendData(0x001D, Buffer.from([ 0x0D, 0x01, 255, bits ]));";

**Comment by robertsLando** [comment]
@AlCalzone do you support bufferAsHex string in sendData?

**Comment by AlCalzone** [comment]
I think it should be the responsibility of zwavejs2mqtt to translate between MQTT commands and the zwave-js method signatures.  Maybe Buffer parameters should be given a special format how they can be marked as such via MQTT, e.g.
```js
{"type": "Buffer", data: "aabbccdd11223344"}
```
to be like the JSON representation of a Buffer, but easier to write
![grafik](https://user-images.githubusercontent.com/17641229/157093266-70bf0ea5-2659-4faf-9e83-0ac3ba1dfccc.png)
