### ISSUE TITLE
[Bug]: Nodes.json can be empty, when no configuration is set

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#2325]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Zwavejs2Mqtt version

6.5.2.c8e6d1a (snap rev 345)

### ZwaveJS version

Unknown

### Describe the bug

I've just started up ZwaveJs2MQTT on my raspberry pi using Snap, and I was testing out restarts to ensure that everything worked before configuring the app. I invoked `zwavejs2mqtt.restart` and then it didn't come back up.

```
# snap logs zwavejs2mqtt -n50
2022-03-19T14:12:47+01:00 systemd[1]: Started Service for snap application zwavejs2mqtt.zwavejs2mqtt.
2022-03-19T14:12:47+01:00 zwavejs2mqtt.zwavejs2mqtt[59114]: Missing plug: «serial-port»
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: 2022-03-19 14:12:53.718 INFO APP: Version: 6.5.2.c8e6d1a
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: 2022-03-19 14:12:53.725 INFO APP: Application path:/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:  ______                       _     ___                  _   _
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: |___  /                      (_)   |__ \                | | | |
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:                             _/ |                      | |
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:                            |__/                       |_|
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: 2022-03-19 14:12:53.783 WARN STORE: scenes.json not found
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: SyntaxError: /var/snap/zwavejs2mqtt/345/nodes.json: Unexpected end of JSON input
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:     at JSON.parse (<anonymous>)
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:     at _readFile (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/node_modules/jsonfile/index.js:25:16)
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:     at StorageHelper._getFile (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server/lib/jsonStore.js:51:20)
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:     at StorageHelper.init (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server/lib/jsonStore.js:42:25)
2022-03-19T14:12:53+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Main process exited, code=exited, status=1/FAILURE
2022-03-19T14:12:53+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Failed with result 'exit-code'.
2022-03-19T14:12:53+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Consumed 7.336s CPU time.
2022-03-19T14:12:54+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Scheduled restart job, restart counter is at 2.
2022-03-19T14:12:54+01:00 systemd[1]: Stopped Service for snap application zwavejs2mqtt.zwavejs2mqtt.
2022-03-19T14:12:54+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Consumed 7.336s CPU time.
2022-03-19T14:12:54+01:00 systemd[1]: Started Service for snap application zwavejs2mqtt.zwavejs2mqtt.
2022-03-19T14:12:54+01:00 zwavejs2mqtt.zwavejs2mqtt[59238]: Missing plug: «serial-port»
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: 2022-03-19 14:13:00.214 INFO APP: Version: 6.5.2.c8e6d1a
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: 2022-03-19 14:13:00.221 INFO APP: Application path:/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:  ______                       _     ___                  _   _
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: |___  /                      (_)   |__ \                | | | |
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:                             _/ |                      | |
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:                            |__/                       |_|
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: 2022-03-19 14:13:00.279 WARN STORE: scenes.json not found
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: SyntaxError: /var/snap/zwavejs2mqtt/345/nodes.json: Unexpected end of JSON input
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:     at JSON.parse (<anonymous>)
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:     at _readFile (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/node_modules/jsonfile/index.js:25:16)
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:     at StorageHelper._getFile (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server/lib/jsonStore.js:51:20)
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:     at StorageHelper.init (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server/lib/jsonStore.js:42:25)
2022-03-19T14:13:00+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Main process exited, code=exited, status=1/FAILURE
2022-03-19T14:13:00+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Failed with result 'exit-code'.
2022-03-19T14:13:00+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Consumed 7.355s CPU time.
2022-03-19T14:13:00+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Scheduled restart job, restart counter is at 3.
2022-03-19T14:13:00+01:00 systemd[1]: Stopped Service for snap application zwavejs2mqtt.zwavejs2mqtt.
2022-03-19T14:13:00+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Consumed 7.355s CPU time.
2022-03-19T14:13:00+01:00 systemd[1]: Started Service for snap application zwavejs2mqtt.zwavejs2mqtt.
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59361]: Missing plug: «serial-port»
```

If I poke at the file, `/var/snap/zwavejs2mqtt/345/nodes.json` its 0 bytes in size.

### To Reproduce

I don't think snap is related to the issue, but it should be something like this:

1. On a clean install, start up zwavejs2mqtt
2. The UI is accessible, if you do, the statistics prompt is shown. Clicking "Ok" will create "settings.json"
3. Do _not_ configure anything else
4. Invoke `zwavejs2mqtt.restart`, this restarts the app
5. Observe that the app does not start, the log shown is logged

### Expected behavior

It seems like there is a code path that can save `nodes.json`, but maybe fail since the zwave device is not configured?

**Comment by kpine** [comment]
I can reproduce with Docker.

If you remove the empty `nodes.json` file you'll also get a different error:

```
2022-03-19 09:16:16.985 WARN STORE: scenes.json not found
2022-03-19 09:16:16.986 WARN STORE: nodes.json not found
2022-03-19 09:16:16.997 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
TypeError: Cannot read property 'disabled' of undefined
    at Gateway.start (/usr/src/app/server/lib/Gateway.js:180:29)
    at startGateway (/usr/src/app/server/app.js:236:14)
    at startServer (/usr/src/app/server/app.js:176:11)
```

I assume some expected setting keys are missing since I never configured anything. `settings.json` content:

```json
{"zwave":{"enableStatistics":false,"disclaimerVersion":1}}
```
