### ISSUE TITLE
[Bug]: Docker 6.11.0 image errors on startup on Raspberry Pi

### ISSUE THREAD

**Issue by emichael** [zwave-js/zwavejs2mqtt#2451]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.11.0

### ZwaveJS version

9.3.0

### Describe the bug

Repeated errors on startup after updating to the latest docker image (`e0b864470128`) on a raspberry pi. My configuration is about a year old and has been through a few updates to zwavejs2mqtt.

Here's the error I get in the docker logs:

```
2022-06-04 23:03:45.849 INFO APP: Version: 6.11.0
2022-06-04 23:03:45.858 INFO APP: Application path:/usr/src/app

 ______                       _     ___                  _   _   
|___  /                      (_)   |__ \                | | | |  
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ 
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ 
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |        
                           |__/                       |_|        

2022-06-04 23:03:45.952 WARN STORE: scenes.json not found
23:03:46.720 DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                      ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                        ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                       ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                      ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                      ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
23:03:46.729 DRIVER   version 9.3.0
23:03:46.732 DRIVER   
23:03:57.525 CONFIG   version 9.3.0
23:04:18.585 CNTRLR   querying controller IDs...
23:04:19.576 CNTRLR   received controller IDs:
                        home ID:     REDACTED
                        own node ID: 1
23:04:19.578 CNTRLR   querying API capabilities...
23:04:19.644 CNTRLR   received API capabilities:
                        firmware version:    4.32
                        manufacturer ID:     0x00
                        product type:        0x01
                        product ID:          0x01
                        supported functions: 
                        · GetSerialApiInitData (0x02)
                        · SetApplicationNodeInformation (0x03)
                        · ApplicationCommand (0x04)
                        · GetControllerCapabilities (0x05)
                        · SetSerialApiTimeouts (0x06)
                        · GetSerialApiCapabilities (0x07)
                        · SoftReset (0x08)
                        · GetProtocolVersion (0x09)
                        · SetRFReceiveMode (0x10)
                        · UNKNOWN_FUNC_SET_SLEEP_MODE (0x11)
                        · FUNC_ID_ZW_SEND_NODE_INFORMATION (0x12)
                        · SendData (0x13)
                        · SendDataMulticast (0x14)
                        · GetControllerVersion (0x15)
                        · SendDataAbort (0x16)
                        · FUNC_ID_ZW_R_F_POWER_LEVEL_SET (0x17)
                        · UNKNOWN_FUNC_SEND_DATA_META (0x18)
                        · FUNC_ID_ZW_GET_RANDOM (0x1c)
                        · GetControllerId (0x20)
                        · UNKNOWN_FUNC_MEMORY_GET_BYTE (0x21)
                        · UNKNOWN_FUNC_MEMORY_PUT_BYTE (0x22)
                        · UNKNOWN_FUNC_MEMORY_GET_BUFFER (0x23)
                        · UNKNOWN_FUNC_MEMORY_PUT_BUFFER (0x24)
                        · UNKNOWN_FUNC_FlashAutoProgSet (0x27)
                        · UNKNOWN_FUNC_UNKNOWN_0x28 (0x28)
                        · GetNVMId (0x29)
                        · ExtNVMReadLongBuffer (0x2a)
                        · ExtNVMWriteLongBuffer (0x2b)
                        · ExtNVMReadLongByte (0x2c)
                        · ExtExtWriteLongByte (0x2d)
                        · GetNodeProtocolInfo (0x41)
                        · HardReset (0x42)
                        · FUNC_ID_ZW_REPLICATION_COMMAND_COMPLETE (0x44)
                        · FUNC_ID_ZW_REPLICATION_SEND_DATA (0x45)
                        · AssignReturnRoute (0x46)
                        · DeleteReturnRoute (0x47)
                        · RequestNodeNeighborUpdate (0x48)
                        · ApplicationUpdateRequest (0x49)
                        · AddNodeToNetwork (0x4a)
                        · RemoveNodeFromNetwork (0x4b)
                        · FUNC_ID_ZW_CREATE_NEW_PRIMARY (0x4c)
                        · FUNC_ID_ZW_CONTROLLER_CHANGE (0x4d)
                        · FUNC_ID_ZW_SET_LEARN_MODE (0x50)
                        · AssignSUCReturnRoute (0x51)
                        · FUNC_ID_ZW_REQUEST_NETWORK_UPDATE (0x53)
                        · SetSUCNodeId (0x54)
                        · DeleteSUCReturnRoute (0x55)
                        · GetSUCNodeId (0x56)
                        · UNKNOWN_FUNC_SEND_SUC_ID (0x57)
                        · FUNC_ID_ZW_EXPLORE_REQUEST_INCLUSION (0x5e)
                        · RequestNodeInfo (0x60)
                        · RemoveFailedNode (0x61)
                        · IsFailedNode (0x62)
                        · ReplaceFailedNode (0x63)
                        · UNKNOWN_FUNC_UNKNOWN_0x66 (0x66)
                        · UNKNOWN_FUNC_UNKNOWN_0x67 (0x67)
                        · UNKNOWN_FUNC_UNKNOWN_0x78 (0x78)
                        · GetRoutingInfo (0x80)
                        · UNKNOWN_FUNC_LOCK_ROUTE_RESPONSE (0x90)
                        · UNKNOWN_FUNC_GET_PRIORITY_ROUTE (0x92)
                        · UNKNOWN_FUNC_SET_PRIORITY_ROUTE (0x93)
                        · UNKNOWN_FUNC_UNKNOWN_0x98 (0x98)
                        · UNKNOWN_FUNC_UNKNOWN_0xB4 (0xb4)
                        · UNKNOWN_FUNC_WATCH_DOG_ENABLE (0xb6)
                        · UNKNOWN_FUNC_WATCH_DOG_DISABLE (0xb7)
                        · UNKNOWN_FUNC_WATCH_DOG_KICK (0xb8)
                        · UNKNOWN_FUNC_UNKNOWN_0xB9 (0xb9)
                        · UNKNOWN_FUNC_RF_POWERLEVEL_GET (0xba)
                        · UNKNOWN_FUNC_GET_LIBRARY_TYPE (0xbd)
                        · UNKNOWN_FUNC_SEND_TEST_FRAME (0xbe)
                        · UNKNOWN_FUNC_GET_PROTOCOL_STATUS (0xbf)
                        · UNKNOWN_FUNC_UNKNOWN_0xD2 (0xd2)
                        · UNKNOWN_FUNC_UNKNOWN_0xD3 (0xd3)
                        · UNKNOWN_FUNC_UNKNOWN_0xD4 (0xd4)
                        · undefined (0xee)
                        · UNKNOWN_FUNC_UNKNOWN_0xEF (0xef)
23:04:19.824 CNTRLR   querying version info...
23:04:19.885 CNTRLR   received version info:
                        controller type: Static Controller
                        library version: Z-Wave 4.05
23:04:19.886 CNTRLR   querying protocol version info...
23:04:19.939 CNTRLR   received protocol version info:
                        protocol type:             Z-Wave
                        protocol version:          4.5.0
23:04:19.944 CNTRLR   supported Z-Wave features: 
23:04:19.945 CNTRLR   querying controller capabilities...
23:04:20.018 CNTRLR   received controller capabilities:
                        controller role:      primary
                        is the SUC:           true
                        started this network: true
                        SIS is present:       true
                        was real primary:     true
23:04:20.020 CNTRLR   finding SUC...
23:04:20.070 CNTRLR   This is the SUC
23:04:20.072 CNTRLR   querying additional controller information...
23:04:20.166 CNTRLR   received additional controller information:
                        Z-Wave API version:         5 (legacy)
                        Z-Wave chip type:           ZW050x
                        node type                   Controller
                        controller role:            primary
                        controller is the SIS:      true
                        controller supports timers: false
                        nodes in the network:       1, 2, 3, 4, 5, 6, 8, 9
23:04:20.273 CNTRLR   [Node 001] Embedded device config loaded
23:04:20.289 CNTRLR   [Node 002] Embedded device config loaded
23:04:20.302 CNTRLR   [Node 003] Embedded device config loaded
23:04:20.314 CNTRLR   [Node 004] Embedded device config loaded
23:04:20.336 CNTRLR   [Node 005] Embedded device config loaded
23:04:20.382 CNTRLR   [Node 006] Embedded device config loaded
23:04:20.448 CNTRLR   [Node 008] Embedded device config loaded
23:04:20.477 CNTRLR   [Node 009] Embedded device config loaded
23:04:20.502 CNTRLR   setting serial API timeouts: ack = 1000 ms, byte = 150 ms
23:04:20.542 CNTRLR   serial API timeouts overwritten. The old values were: ack = 1000 ms, byte = 15
                      0 ms
23:04:20.543 CNTRLR   Interview completed
23:04:20.747 CNTRLR   [Node 001] The node is alive.
23:04:20.761 CNTRLR   [Node 001] The node is ready to be used
23:04:20.764 CNTRLR » [Node 002] pinging the node...
23:04:21.063 CNTRLR » [Node 003] pinging the node...
23:04:21.070 CNTRLR » [Node 004] pinging the node...
23:04:21.078 CNTRLR » [Node 005] pinging the node...
23:04:21.084 CNTRLR » [Node 006] pinging the node...
23:04:21.095 CNTRLR   [Node 008] The node is asleep.
23:04:21.226 CNTRLR   [Node 008] The node is ready to be used
23:04:21.231 CNTRLR   [Node 009] The node is asleep.
23:04:21.341 CNTRLR   [Node 009] The node is ready to be used
23:04:21.515 CNTRLR   [Node 002] The node is alive.
23:04:23.162 CNTRLR   [Node 002] The node is ready to be used
23:04:23.175 CNTRLR « [Node 002] ping successful
23:04:23.266 CNTRLR   [Node 003] The node is alive.
23:04:24.307 CNTRLR   [Node 003] The node is ready to be used
23:04:24.318 CNTRLR « [Node 003] ping successful
23:04:24.820 CNTRLR   [Node 004] The node is alive.
23:04:25.762 CNTRLR   [Node 004] The node is ready to be used
23:04:25.774 CNTRLR « [Node 004] ping successful
23:04:25.952 CNTRLR   [Node 005] The node is alive.
23:04:26.001 CNTRLR   [Node 005] The node is ready to be used
23:04:26.012 CNTRLR « [Node 005] ping successful
23:04:26.076 CNTRLR   [Node 006] The node is alive.
23:04:26.216 CNTRLR   [Node 006] The node is ready to be used
23:04:26.218 CNTRLR   All nodes are ready to be used
23:04:26.225 CNTRLR « [Node 006] ping successful
2022-06-04 23:14:32.177 WARN APP: Shutdown detected: closing clients...
/usr/src/app/node_modules/shebang-command/index.js:1
REDACTED_WEIRD_UNPRINTABLE_BYTESTRING
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1039:15)
    at Module._compile (node:internal/modules/cjs/loader:1073:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/src/app/node_modules/cross-spawn/lib/util/readShebang.js:4:24)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
/usr/src/app/node_modules/shebang-command/index.js:1
REDACTED_WEIRD_UNPRINTABLE_BYTESTRING
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1039:15)
    at Module._compile (node:internal/modules/cjs/loader:1073:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/src/app/node_modules/cross-spawn/lib/util/readShebang.js:4:24)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
```
That error prints 15 times or so, and then the container tries to restart with the same error.

### To Reproduce

My docker-compose.yml:
```
# docker-compose.yml
version: "2"

services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      SESSION_SECRET: "XXXXXXXXX"
      TZ: America/Los_Angeles
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./docker-mounts/zwavejs2mqtt:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface
```

### Expected behavior

The container should start without error.

### Additional context

```
$ uname -a
Linux rpi1 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

**Comment by robertsLando** [comment]
@AlCalzone any clue what could be the root cause? I don't use that package on my side

**Comment by AlCalzone** [comment]
No clue. Cross-spawn is for process spawning, the driver doesn't do that.

**Comment by robertsLando** [comment]
By using `yarn why` command it turned out it's a zwave-js dependency from `execa` package

**Comment by AlCalzone** [comment]
Oh. Right. But it only does that when installing config updates outside of docker.
The error message above looks like corrupted js files.

**Comment by emichael** [comment]
Oh, I forgot to mention. After I downgraded back to the previous working version (6.9.1), everything was still fine, and the controller started up without issue.

**Comment by robertsLando** [comment]
@emichael Do you have logging set to debug level? You should tyy to set both z2m and zwavejs logging to that level and then upgrade, maybe we can see something more to debug this because that error doesn't tell us what caused it
