### ISSUE TITLE
[Bug]: Driver fails to start with targeted serial port 						

### ISSUE THREAD

**Issue by Lovasz-Akos** [zwave-js/zwavejs2mqtt#2518]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install)

### Zwavejs2Mqtt version

6.13.0

### ZwaveJS version

9.5.0

### Describe the bug

trying to start the service with the correct serial port targeted throws:
```
Driver: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/home/smarthome/zwavejs2mqtt-6.13.0/node_modules/zwave-js/src/lib/driver/Driver.ts:3547:23)
    at ZWaveController.identify (/home/smarthome/zwavejs2mqtt-6.13.0/node_modules/zwave-js/src/lib/controller/Controller.ts:724:33)
    at Driver.initializeControllerAndNodes (/home/smarthome/zwavejs2mqtt-6.13.0/node_modules/zwave-js/src/lib/driver/Driver.ts:1117:26)
    at Immediate.<anonymous> (/home/smarthome/zwavejs2mqtt-6.13.0/node_modules/zwave-js/src/lib/driver/Driver.ts:924:16) (ZW0100)
```

"silly" log output:
```
14:50:49.416 DRIVER   version 9.5.0
14:50:49.417 DRIVER
14:50:49.418 DRIVER   starting driver...
14:50:49.426 DRIVER   opening serial port /dev/ttyS1
14:50:49.435 DRIVER   serial port opened
14:50:49.437 SERIAL » [NAK]                                                                   (0x15)
14:50:49.441 DRIVER   loading configuration...
14:50:49.445 CONFIG   version 9.5.0
14:50:51.653 DRIVER   beginning interview...
14:50:51.655 DRIVER   added request handler for AddNodeToNetwork (0x4a)...
                      1 registered
14:50:51.657 DRIVER   added request handler for RemoveNodeFromNetwork (0x4b)...
                      1 registered
14:50:51.658 DRIVER   added request handler for ReplaceFailedNode (0x63)...
                      1 registered
14:50:51.660 CNTRLR   querying controller IDs...
14:50:51.704 SERIAL » 0x01030020dc                                                         (5 bytes)
14:50:51.708 DRIVER » [REQ] [GetControllerId]
14:50:52.729 CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                      n 100 ms.
14:50:52.837 SERIAL » 0x01030020dc                                                         (5 bytes)
14:50:52.840 DRIVER » [REQ] [GetControllerId]
14:50:53.847 CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                      n 1100 ms.
14:50:54.951 SERIAL » 0x01030020dc                                                         (5 bytes)
14:50:54.954 DRIVER » [REQ] [GetControllerId]
14:50:55.972 DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK
                      from the controller (ZW0200)
                          at Driver.sendMessage (/home/smarthome/zwavejs2mqtt-6.13.0/node_modules/zw
                      ave-js/src/lib/driver/Driver.ts:3547:23)
                          at ZWaveController.identify (/home/smarthome/zwavejs2mqtt-6.13.0/node_modu
                      les/zwave-js/src/lib/controller/Controller.ts:724:33)
                          at Driver.initializeControllerAndNodes (/home/smarthome/zwavejs2mqtt-6.13.
                      0/node_modules/zwave-js/src/lib/driver/Driver.ts:1117:26)
                          at Immediate.<anonymous> (/home/smarthome/zwavejs2mqtt-6.13.0/node_modules
                      /zwave-js/src/lib/driver/Driver.ts:924:16)
14:50:55.978 DRIVER   destroying driver instance...
14:50:55.984 DRIVER   driver instance destroyed
```

### To Reproduce

- Start zwavejs2mqtt with npm start
- Put /dev/ttyS1 into the serial port config section

### Expected behavior

It recognizes the com port and proceeds to start the driver

### Additional context

If I target ttyS1 insted of /dev/ttyS1, I get this error:
```
Driver: Failed to open the serial port: Error: No such file or directory, cannot open ttyS1 (ZW0100)						
```

**Comment by robertsLando** [comment]
@Lovasz-Akos Are you 100% sure that ttyS1 is correct? What controller are you using?

**Comment by Lovasz-Akos** [comment]
ttyS1 *should* be correct (unless my boss gave me the wrong port before going on a 2 week vacation lol), and I'm not sure about the controller (any way to check?)

**Comment by robertsLando** [comment]
Try to use serial-by-id path: https://github.com/zwave-js/zwavejs2mqtt/discussions/2483

**Comment by Lovasz-Akos** [comment]
you're right, `/bin/udevadm info --name=/dev/ttyS1 | grep SERIAL` returned nothing,
`ls /dev/serial/by-id/` returned `usb-1a86_USB_Serial-if00-port0`

**Comment by Lovasz-Akos** [comment]
oh, running it without grep returned me this
```
P: /devices/platform/ff120000.serial/tty/ttyS1
N: ttyS1
L: 0
E: DEVPATH=/devices/platform/ff120000.serial/tty/ttyS1
E: DEVNAME=/dev/ttyS1
E: MAJOR=4
E: MINOR=65
E: SUBSYSTEM=tty
E: USEC_INITIALIZED=6084680
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```

**Comment by robertsLando** [comment]
Ok so try using

`/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0`

**Comment by Lovasz-Akos** [comment]
still times out on ACK ` Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK
                      from the controller (ZW0200)`

**Comment by kpine** [comment]
`/dev/ttyS1` is definitely not the path of a USB serial device. What kind of Z-Wave module is this? Even the by-id path is strange. Typically, 700-series USB controllers get the path `/dev/ttyUSB0` and have a much longer by-id path, e.g.

```console
$ ls /dev/ttyUSB0
/dev/ttyUSB0
$ ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Jul  6 00:55 usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_7a6bb087ac08ea11b486db812473482f-if00-port0 -> ../../ttyUSB0
```

What is your `/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0` symlink pointing to? What does udev say about the symlink? `udevadm info -q property -n /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0`.

**Comment by Lovasz-Akos** [comment]
Looks like I forgot to mention, the Z-Wave module is not a USB device! 
using `dmesg | grep tty` it looks to me that some service is actually using the port and denying me access.
```
[    0.232614] Registered FIQ tty driver
[    0.887646] console [ttyFIQ0] enabled
[    0.891788] Registered fiq debugger ttyFIQ0
[    1.998402] ff110000.serial: ttyS0 at MMIO 0xff110000 (irq = 10, base_baud = 1500000) is a 16550A
[    2.008419] ff120000.serial: ttyS1 at MMIO 0xff120000 (irq = 11, base_baud = 1500000) is a 16550A
[    4.466169] usb 2-1.2: ch341-uart converter now attached to ttyUSB0
[    4.656764] usb 2-1.3: ch341-uart converter now attached to ttyUSB1
[    5.781658] systemd[1]: Created slice Slice /system/serial-getty.
[    6.063176] ttyS1 - failed to request DMA, use interrupt mode
[    9.952815] tty_port_close_start: tty->count = 1 port count = 2.
[ 4189.950580] ttyS0 - failed to request DMA, use interrupt mode
```
Time to find the culprit, looks like I found the root of the problem

**Comment by Lovasz-Akos** [comment]
ps: yep, found the service hogging the port, all work fine now!
