### ISSUE TITLE
[bug] Dimmer 2 (Fibargroup - FGD212) - Error while writing 50 on 38-0-targetValue: Timed out.

### ISSUE THREAD

**Issue by lucguinchard** [zwave-js/zwavejs2mqtt#253]
Hello Daniel, Buongiorno,

**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: 1.0.0-beta.0.6e2a0f7

**Describe the bug**

On my device `Dimmer 2 (FGD212)`, when I change the value `38-0-currentValue` An exception is raised:

![image](https://user-images.githubusercontent.com/17431299/104760778-2b4fe580-5762-11eb-96db-45d1713385e4.png)

```BASH
2021-01-15 18: 44: 06.273 INFO APP: Zwave api call: writeValue [{nodeId: 11,
    commandClass: 38,
    endpoint: 0,
    property: 'targetValue'},
  50,
  [length]: 2]
2021-01-15 18: 44: 06.274 INFO ZWAVE: Writing 50 to 38-0-targetValue
2021-01-15 18: 44: 16.362 ERROR ZWAVE: Error while writing 50 on 38-0-targetValue: Timed out while waiting for a response from the node Timed out while waiting for a response from the node
ZWaveError: Timed out while waiting for a response from the node
    at Object.sendDataErrorToZWaveError (/home/pi/zwavejs2mqtt/node_modules/zwave-js/src/lib/driver/StateMachineShared.ts:150:11)
    at xstate_1.assign (/home/pi/zwavejs2mqtt/node_modules/zwave-js/src/lib/driver/SendThreadMachine.ts:462:4)
    at /home/pi/zwavejs2mqtt/node_modules/xstate/lib/utils.js:410:33
    at Array.reduce (<anonymous>)
    at Object.updateContext (/home/pi/zwavejs2mqtt/node_modules/xstate/lib/utils.js:400:25)
    at Object.resolveActions (/home/pi/zwavejs2mqtt/node_modules/xstate/lib/actions.js:409:19)
    at StateNode.resolveTransition (/home/pi/zwavejs2mqtt/node_modules/xstate/lib/StateNode.js:787:35)
    at StateNode.transition (/home/pi/zwavejs2mqtt/node_modules/xstate/lib/StateNode.js:733:21)
    at /home/pi/zwavejs2mqtt/node_modules/xstate/lib/interpreter.js:602:34
    at Object.provide (/home/pi/zwavejs2mqtt/node_modules/xstate/lib/serviceScope.js:11:18)
    at Interpreter.nextState (/home/pi/zwavejs2mqtt/node_modules/xstate/lib/interpreter.js:601:38)
    at /home/pi/zwavejs2mqtt/node_modules/xstate/lib/interpreter.js:124:39
    at Scheduler.process (/home/pi/zwavejs2mqtt/node_modules/xstate/lib/scheduler.js:60:13)
    at Scheduler.schedule (/home/pi/zwavejs2mqtt/node_modules/xstate/lib/scheduler.js:44:14)
    at Interpreter.send (/home/pi/zwavejs2mqtt/node_modules/xstate/lib/interpreter.js:121:29)
    at Timeout. <anonymous> (/home/pi/zwavejs2mqtt/node_modules/xstate/lib/interpreter.js:633:23)
2021-01-15 18: 44: 16.364 ERROR ZWAVE: Unable to write 50 on 38-0-targetValue
2021-01-15 18: 44: 16.364 INFO ZWAVE: Success zwave api call writeValue
```
Thanks.

**Comment by bdbogjoe** [comment]
i have such device, and did not face any issue with it, how can i help ?

**Comment by lucguinchard** [comment]
Hello, (Merci de ton retour)
I have 6 devices of this type. None of them work.
The program runs on an RPI4.
Node version : v10.23.1.

**Comment by bdbogjoe** [comment]
you can contact me on zwave2mqtt.slack.com, we can discuss and check differences

**Comment by bdbogjoe** [comment]
here my config with zigbeee2mqtt
`
version: '3.7'
services:
  zwave2mqtt:
    container_name: zwave2mqtt
    image: zwavejs/zwavejs2mqtt:1.0.0-beta.0
    restart: always
    tty: true
    stop_signal: SIGINT
    networks:
      - mqtt
    devices:
      - '/dev/ttyACM10:/dev/ttyACM10'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zwave/store:/usr/src/app/store
    ports:
      - '8091:8091'
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: always
    tty: true
    stop_signal: SIGINT
    networks:
      - mqtt
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zigbee/store:/app/data
    ports:
      - '8080:8080'
networks:
  mqtt:
`

**Comment by robertsLando** [comment]
Is this fixed?

**Comment by bdbogjoe** [comment]
no news from him, maybe after working hours

**Comment by lucguinchard** [comment]
Sorry for this late return.
I don't have Slack. My Z-wave key is a GPIO key for RPI.
I will try to do some new tests soon.
Is there a recommended version of NodeJS and npm?

**Comment by robertsLando** [comment]
> Is there a recommended version of NodeJS and npm?

Use latest LTS (node 14)

**Comment by sirfooey** [comment]
My FGD212 has the Target brightness at "-1" instead of "-0" as opposed to the OP's screenshot

That is: node 52 : [52-38-1-targetValue], I can change this setting and it works fine.

Though when turning on the dimmer using the toggle in HA, it turns on back to full brightness, rather than respecting the last brightness level (not sure if this is a user error or a bug)

**Comment by lucguinchard** [comment]
I have updated my RPI4 (apt full-upgrade, z-way), open-zwave and nodeJS (14.15.4), npm (6.14.10) and also zwavejs2mqtt.

I still have the same problem: `Timed out while waiting for a response from the node.
However, I don't have the stack.`

I have not yet tested with a docker.

Is there a way to update fibaro devices?

Thank you all.

**Comment by lucguinchard** [comment]
I just installed docker on the RPI4.
I still have the error:
```
2021-01-24 18:52:49.045 ERROR ZWAVE: Error while writing 20 on 38-0-targetValue: Timed out while waiting for a response from the node Timed out while waiting for a response from the node
ZWaveError: Timed out while waiting for a response from the node
    at Object.sendDataErrorToZWaveError (/usr/src/app/node_modules/zwave-js/src/lib/driver/StateMachineShared.ts:150:11)
    at /usr/src/app/node_modules/zwave-js/src/lib/driver/SendThreadMachine.ts:462:4
    at /usr/src/app/node_modules/xstate/lib/utils.js:410:33
    at Array.reduce (<anonymous>)
    at Object.updateContext (/usr/src/app/node_modules/xstate/lib/utils.js:400:25)
    at Object.resolveActions (/usr/src/app/node_modules/xstate/lib/actions.js:409:19)
    at StateNode.resolveTransition (/usr/src/app/node_modules/xstate/lib/StateNode.js:787:35)
    at StateNode.transition (/usr/src/app/node_modules/xstate/lib/StateNode.js:733:21)
    at /usr/src/app/node_modules/xstate/lib/interpreter.js:602:34
    at Object.provide (/usr/src/app/node_modules/xstate/lib/serviceScope.js:11:18)
    at Interpreter.nextState (/usr/src/app/node_modules/xstate/lib/interpreter.js:601:38)
    at /usr/src/app/node_modules/xstate/lib/interpreter.js:124:39
    at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:60:13)
    at Scheduler.schedule (/usr/src/app/node_modules/xstate/lib/scheduler.js:44:14)
    at Interpreter.send (/usr/src/app/node_modules/xstate/lib/interpreter.js:121:29)
    at Timeout.<anonymous> (/usr/src/app/node_modules/xstate/lib/interpreter.js:633:23)

```

**Comment by robertsLando** [comment]
@lucguinchard I need the zwavejs logs

**Comment by lucguinchard** [comment]
Hello,
I have update : 
![image](https://user-images.githubusercontent.com/17431299/106268708-c13c4380-622b-11eb-8eec-d39a4a914d80.png)

I have no more errors, but the lamp still does not light up :
```
2021-01-29 12:01:16.982 INFO ZWAVE: Calling api writeValue with args: [
  {
    nodeId: 11,
    commandClass: 38,
    endpoint: 0,
    property: 'targetValue'
  },
  200,
  [length]: 2
]
2021-01-29 12:01:16.989 INFO ZWAVE: Writing 200 to 11-38-0-targetValue
2021-01-29 12:01:17.036 INFO ZWAVE: Success zwave api call writeValue { success: true, message: 'Success zwave api call', result: undefined }
```

Otherwise if I activate the lamp with a physical button, the number of watt used is modified.

I activated the logs:
![image](https://user-images.githubusercontent.com/17431299/106269065-46bff380-622c-11eb-829b-2643fce1a8e9.png)

And change target value to 200 of `Node 011` :

```
12:31:59.326 DRIVER « [RES] [SendData]
                        was sent: true
12:31:59.333 CNTRLR   [Node 009] MultilevelSensorCC: doing a partial interview...
12:31:59.334 CNTRLR » [Node 009] querying current sensor reading...
12:31:59.340 SERIAL « 0x011800130a000002007e7f7f7f7f000003000000000301000083              (26 bytes)
12:31:59.340 SERIAL » [ACK]                                                                   (0x06)
12:31:59.341 DRIVER « [REQ] [SendData]
                        callback id:     10
                        transmit status: OK
12:32:09.358 SERIAL » 0x010a00130b032601c8250b2f                                          (12 bytes)
12:32:09.360 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      11
                      └─[MultilevelSwitchCCSet]
                          target value: 200
12:32:09.389 SERIAL « [ACK]                                                                   (0x06)
12:32:09.393 SERIAL « 0x0104011301e8                                                       (6 bytes)
12:32:09.394 SERIAL » [ACK]                                                                   (0x06)
12:32:09.396 DRIVER « [RES] [SendData]
                        was sent: true
12:32:09.402 SERIAL « 0x011800130b00000200d77f7f7f7f00000300000000030100002b              (26 bytes)
12:32:09.403 SERIAL » [ACK]                                                                   (0x06)
12:32:09.405 CNTRLR   [Node 010] MultilevelSensorCC: doing a partial interview...
12:32:09.406 CNTRLR » [Node 010] querying current sensor reading...
12:32:09.414 DRIVER « [REQ] [SendData]
                        callback id:     11
                        transmit status: OK
12:32:09.436 SERIAL » 0x010900130b022606250ce5                                            (11 bytes)
12:32:09.437 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      12
                      └─[MultilevelSwitchCCSupportedGet]
12:32:09.442 SERIAL « [ACK]                                                                   (0x06)
12:32:09.444 SERIAL « 0x0104011301e8                                                       (6 bytes)
12:32:09.445 SERIAL » [ACK]                                                                   (0x06)
12:32:09.446 DRIVER « [RES] [SendData]
                        was sent: true
12:32:09.462 SERIAL « 0x011800130c00000200d77f7f7f7f00000300000000030100002c              (26 bytes)
12:32:09.463 SERIAL » [ACK]                                                                   (0x06)
12:32:09.465 DRIVER « [REQ] [SendData]
                        callback id:     12
                        transmit status: OK
12:32:19.484 SERIAL » 0x010900130b022602250de0                                            (11 bytes)
12:32:19.485 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      13
                      └─[MultilevelSwitchCCGet]
12:32:19.501 SERIAL « [ACK]                                                                   (0x06)
12:32:19.503 SERIAL « 0x0104011301e8                                                       (6 bytes)
12:32:19.503 SERIAL » [ACK]                                                                   (0x06)
12:32:19.505 DRIVER « [RES] [SendData]
                        was sent: true
12:32:19.508 CNTRLR   [Node 011] MultilevelSensorCC: doing a partial interview...
12:32:19.509 CNTRLR » [Node 011] querying current sensor reading...
12:32:19.514 SERIAL « 0x011800130d00000200d77f7f7f7f00000300000000030100002d              (26 bytes)
12:32:19.515 SERIAL » [ACK]                                                                   (0x06)
12:32:19.516 DRIVER « [REQ] [SendData]
                        callback id:     13
                        transmit status: OK
12:32:29.531 SERIAL » 0x010900130c022606250ee0                                            (11 bytes)
12:32:29.533 DRIVER » [Node 012] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      14
                      └─[MultilevelSwitchCCSupportedGet]
```

Thanks,

**Comment by robertsLando** [comment]
@lucguinchard is your issue fixed?
