### ISSUE TITLE
Latest dev docker - what happened to my node info?

### ISSUE THREAD

**Issue by Swiftnesses** [zwave-js/zwavejs2mqtt#267]
Just updated now, control panel is now missing some node info (most battery ones, some mains powered ones).

<img width="1854" alt="Screenshot 2021-01-18 at 21 29 46" src="https://user-images.githubusercontent.com/1001877/104964532-77a25c00-59d4-11eb-8ce6-8fa07966a897.png">

**Comment by Swiftnesses** [comment]
Also, when I click debug, I get:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: this.driver.configManager.getMeterName is not a function
at MeterCC.translatePropertyKey (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/MeterCC.ts:472:40)
at ZWaveNode.translateValueID (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:268:35)
at ZWaveNode.translateValueEvent (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:285:23)
at ValueDB.emit (events.js:314:20)
at ValueDB.EventEmitter.emit (domain.js:483:12)
at ValueDB.setValue (/usr/src/app/node_modules/@zwave-js/core/src/values/ValueDB.ts:224:10)
at MeterCCReport.persistValues (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/MeterCC.ts:620:11)
at new MeterCCReport (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/MeterCC.ts:551:8)
at new CommandClass (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/CommandClass.ts:108:13)
at new MeterCC (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/MeterCC.ts:285:1)
at Function.from (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/CommandClass.ts:331:15)
at new ApplicationCommandRequest (/usr/src/app/node_modules/zwave-js/src/lib/controller/ApplicationCommandRequest.ts:83:32)
at Function.from (/usr/src/app/node_modules/zwave-js/src/lib/message/Message.ts:222:15)
at Driver.serialport_onData (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1362:18)
at SerialAPIParser.emit (events.js:314:20)
at SerialAPIParser.EventEmitter.emit (domain.js:483:12)
```

**Comment by Swiftnesses** [comment]
Reverted back to 'latest' and it's working again - appears to be an issue with the dev docker.

**Comment by robertsLando** [comment]
@Swiftnesses Let me check this. 

cc @AlCalzone

**Comment by robertsLando** [comment]
@Swiftnesses Could you try to pull last `dev` tag please?

**Comment by Swiftnesses** [comment]
Just pulled dev and it still crashes - I'll try and capture the error.

**Comment by Swiftnesses** [comment]
@robertsLando:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:


TypeError: this.driver.configManager.getMeterName is not a function


    at MeterCC.translatePropertyKey (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/MeterCC.ts:472:40)


    at ZWaveNode.translateValueID (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:268:35)


    at ZWaveNode.translateValueEvent (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:285:23)


    at ValueDB.emit (events.js:314:20)


    at ValueDB.EventEmitter.emit (domain.js:483:12)


    at ValueDB.setValue (/usr/src/app/node_modules/@zwave-js/core/src/values/ValueDB.ts:224:10)


    at MeterCCReport.persistValues (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/MeterCC.ts:620:11)


    at new MeterCCReport (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/MeterCC.ts:551:8)


    at new CommandClass (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/CommandClass.ts:108:13)


    at new MeterCC (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/MeterCC.ts:285:1)


    at Function.from (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/CommandClass.ts:331:15)


    at new ApplicationCommandRequest (/usr/src/app/node_modules/zwave-js/src/lib/controller/ApplicationCommandRequest.ts:83:32)


    at Function.from (/usr/src/app/node_modules/zwave-js/src/lib/message/Message.ts:222:15)


    at Driver.serialport_onData (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1362:18)


    at SerialAPIParser.emit (events.js:314:20)


    at SerialAPIParser.EventEmitter.emit (domain.js:483:12)
```

**Comment by Swiftnesses** [comment]
Looks to be the same error as before ^^^ ?

**Comment by AlCalzone** [comment]
This means there is some wrong version of `@zwave-js/config` in the image. Don't know why though.

**Comment by AlCalzone** [comment]
https://unpkg.com/browse/zwave-js@6.0.0-beta.3/build/lib/commandclass/MeterCC.js#L334
uses:
https://unpkg.com/browse/@zwave-js/config@6.0.0-beta.3/build/ConfigManager.js#L223

**Comment by robertsLando** [comment]
I'm quite sure this is a user issue, @Swiftnesses pplease try with a clean installation to see if this happens. I have just rteleased a new version now

**Comment by Swiftnesses** [comment]
@robertsLando I use Docker and always wipe out my install (only the config files are retained).

It still happens using the latest version (lastest, still works, for now).

**Comment by robertsLando** [comment]
@Swiftnesses I cannot reproduce this, I suggest you to remove the dev image completely from your pc and pull it again

**Comment by Swiftnesses** [comment]
I always do this... I'll look when there's more time - I don't think it's a use case though.
