### ISSUE TITLE
[bug] Building36 T10 (ADC T-2000) thermostat compat flags

### ISSUE THREAD

**Issue by bachya** [zwave-js/zwavejs2mqtt#375]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: 1.0.0-alpha.2

**Describe the bug**
I am attempting to get my [Building 36 T10 thermostat](https://products.z-wavealliance.org/products/1161) working with Home Assistant and am unable to see the `climate` entity as a device within z2m.

First, I gather from the docs that devices in the `climate` Home Assistant domain need to have a configuration provided. I wrote this configuration:

```json
{
 "400-1-1": [
  {
   "type": "climate",
   "object_id": "thermostat",
   "values": [
    "49-1-Air temperature",
    "64-0-mode",
    "66-0-state",
    "67-1-setpoint-1",
    "67-1-setpoint-2",
    "68-0-mode"
   ],
   "mode_map": {
    "off": 0,
    "heat": 1,
    "cool": 2,
    "auto": 3
   },
   "fan_mode_map": {
    "auto_low": 0,
    "on_low": 1,
    "circulate": 6
   },
   "setpoint_topic": {
    "heat": "67-1-setpoint-1",
    "cool": "67-1-setpoint-2"
   },
   "default_setpoint": "67-1-setpoint-1",
   "discovery_payload": {
    "min_temp": 50,
    "max_temp": 85,
    "modes": [
     "off",
     "heat",
     "cool",
     "auto"
    ],
    "fan_modes": [
     "auto_low",
     "on_low",
     "circulate"
    ],
    "action_topic": "66-0-state",
    "action_template": "{{ value_json.value | lower }}",
    "current_temperature_topic": "49-1-Air temperature",
    "current_temperature_template": "{{ value_json.value }}",
    "fan_mode_state_topic": "68-0-mode",
    "fan_mode_command_topic": true,
    "mode_state_topic": "64-0-mode",
    "mode_command_topic": true,
    "temperature_state_template": "{{ value_json.value }}",
    "temperature_command_topic": true
   }
  }
 ]
}
```

...and stored it in `store/customDevices.json`. I didn't find those docs especially clear, but I tried to follow the format and used the data from [the OZW database](https://github.com/OpenZWave/open-zwave/blob/master/config/building36/b36-t10.xml) (which I also wrote).

I am able to see the node when `zwavejs2mqtt` loads:

<img width="1157" alt="Screen Shot 2021-01-07 at 4 42 45 PM" src="https://user-images.githubusercontent.com/47216/103957253-8b61de80-5107-11eb-927c-a6518b8a17e0.png">

I am able to see four `binary_sensor`/`sensor` devices:

<img width="592" alt="Screen Shot 2021-01-07 at 4 44 56 PM" src="https://user-images.githubusercontent.com/47216/103957308-ae8c8e00-5107-11eb-85dc-267cecff7afe.png">

...but the `climate` device is missing. No amount of refreshing the node, rediscovering the devices, etc. changes that.

**Additional context**
I do see this error in the Docker console logs (which are the gateway logs, I assume):

```
2021-01-07 23:55:10.417 INFO ZWAVE: Node 2: value updated: 128-0-level 0 => 0
2021-01-07 23:55:10.418 INFO ZWAVE: Node 2: value updated: 128-0-isLow false => false
2021-01-07 23:55:10.426 INFO ZWAVE: Node 2 is alive
2021-01-07 23:55:10.492 INFO ZWAVE: Node 2: value added 2-49-0-Air temperature => 20.62
2021-01-07 23:55:10.493 INFO ZWAVE: Node 2: value added 2-49-0-Humidity => 29
2021-01-07 23:55:10.494 INFO ZWAVE: Node 2: value added 2-64-0-mode => 1
2021-01-07 23:55:10.494 INFO MQTT: Subscribing to zwavejs2mqtt/+/+/+/+/set
2021-01-07 23:55:10.495 INFO ZWAVE: Node 2: value added 2-64-0-manufacturerData => undefined
2021-01-07 23:55:10.495 INFO ZWAVE: Node 2: value added 2-66-0-state => 8
2021-01-07 23:55:10.496 INFO ZWAVE: Node 2: value added 2-112-0-1 => 0
2021-01-07 23:55:10.496 INFO ZWAVE: Node 2: value added 2-112-0-2 => 2
2021-01-07 23:55:10.496 INFO ZWAVE: Node 2: value added 2-112-0-3 => 2
2021-01-07 23:55:10.497 INFO ZWAVE: Node 2: value added 2-112-0-4 => 1
2021-01-07 23:55:10.497 INFO ZWAVE: Node 2: value added 2-112-0-5 => 704643072
2021-01-07 23:55:10.497 INFO ZWAVE: Node 2: value added 2-112-0-6 => 704644352
2021-01-07 23:55:10.498 INFO ZWAVE: Node 2: value added 2-112-0-7 => 704643072
2021-01-07 23:55:10.498 INFO ZWAVE: Node 2: value added 2-112-0-8 => 10
2021-01-07 23:55:10.498 INFO ZWAVE: Node 2: value added 2-112-0-9 => 10
2021-01-07 23:55:10.499 INFO ZWAVE: Node 2: value added 2-112-0-10 => 704732672
2021-01-07 23:55:10.499 INFO ZWAVE: Node 2: value added 2-112-0-11 => 0
2021-01-07 23:55:10.499 INFO ZWAVE: Node 2: value added 2-112-0-12 => 20
2021-01-07 23:55:10.500 INFO ZWAVE: Node 2: value added 2-112-0-13 => 25
2021-01-07 23:55:10.500 INFO ZWAVE: Node 2: value added 2-112-0-14 => 60
2021-01-07 23:55:10.500 INFO ZWAVE: Node 2: value added 2-112-0-15 => 704886272
2021-01-07 23:55:10.500 INFO ZWAVE: Node 2: value added 2-112-0-16 => 704732672
2021-01-07 23:55:10.501 INFO ZWAVE: Node 2: value added 2-112-0-17 => 704886272
2021-01-07 23:55:10.501 INFO ZWAVE: Node 2: value added 2-112-0-18 => 704771072
2021-01-07 23:55:10.501 INFO ZWAVE: Node 2: value added 2-112-0-19 => 0
2021-01-07 23:55:10.502 INFO ZWAVE: Node 2: value added 2-112-0-20 => 5
2021-01-07 23:55:10.502 INFO ZWAVE: Node 2: value added 2-112-0-21 => 10
2021-01-07 23:55:10.502 INFO ZWAVE: Node 2: value added 2-112-0-22 => 25
2021-01-07 23:55:10.502 INFO ZWAVE: Node 2: value added 2-112-0-23 => 1
2021-01-07 23:55:10.503 INFO ZWAVE: Node 2: value added 2-112-0-24 => 15
2021-01-07 23:55:10.503 INFO ZWAVE: Node 2: value added 2-112-0-25 => 0
2021-01-07 23:55:10.503 INFO ZWAVE: Node 2: value added 2-112-0-26 => 1
2021-01-07 23:55:10.504 INFO ZWAVE: Node 2: value added 2-112-0-27 => 30
2021-01-07 23:55:10.504 INFO ZWAVE: Node 2: value added 2-112-0-28 => 15
2021-01-07 23:55:10.504 INFO ZWAVE: Node 2: value added 2-112-0-30 => 0
2021-01-07 23:55:10.505 INFO ZWAVE: Node 2: value added 2-112-0-31 => 704650752
2021-01-07 23:55:10.505 INFO ZWAVE: Node 2: value added 2-112-0-32 => 704650752
2021-01-07 23:55:10.505 INFO ZWAVE: Node 2: value added 2-112-0-33 => 704645632
2021-01-07 23:55:10.505 INFO ZWAVE: Node 2: value added 2-112-0-34 => 1
2021-01-07 23:55:10.506 INFO ZWAVE: Node 2: value added 2-112-0-35 => 0
2021-01-07 23:55:10.506 INFO ZWAVE: Node 2: value added 2-114-0-manufacturerId => 400
2021-01-07 23:55:10.506 INFO ZWAVE: Node 2: value added 2-114-0-productType => 1
2021-01-07 23:55:10.506 INFO ZWAVE: Node 2: value added 2-114-0-productId => 1
2021-01-07 23:55:10.507 INFO ZWAVE: Node 2: value added 2-128-0-level => 0
2021-01-07 23:55:10.507 INFO ZWAVE: Node 2: value added 2-128-0-isLow => false
2021-01-07 23:55:10.507 INFO ZWAVE: Node 2: value added 2-134-0-libraryType => 3
2021-01-07 23:55:10.508 INFO ZWAVE: Node 2: value added 2-134-0-protocolVersion => 4.54
2021-01-07 23:55:10.508 INFO ZWAVE: Node 2: value added 2-134-0-firmwareVersions => 1.20
2021-01-07 23:55:10.508 INFO ZWAVE: Node 2: value added 2-134-0-hardwareVersion => undefined
2021-01-07 23:55:10.511 ERROR GATEWAY: Error while discovering device climate_thermostat of node 2: Cannot read property 'id' of undefined Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
    at Gateway.valueTopic (/usr/src/app/lib/Gateway.js:868:23)
    at Gateway.discoverDevice (/usr/src/app/lib/Gateway.js:1126:16)
    at /usr/src/app/lib/Gateway.js:360:40
    at Array.forEach (<anonymous>)
    at Gateway.onNodeStatus (/usr/src/app/lib/Gateway.js:360:17)
    at ZwaveClient.emit (events.js:314:20)
    at ZwaveClient.EventEmitter.emit (domain.js:483:12)
    at ZwaveClient.onNodeStatus (/usr/src/app/lib/ZwaveClient.js:255:10)
    at ZwaveClient.onNodeReady (/usr/src/app/lib/ZwaveClient.js:283:16)
    at ZWaveNode.emit (events.js:326:22)
    at ZWaveNode.EventEmitter.emit (domain.js:483:12)
    at ZWaveNode.onReadyChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:441:19)
    at /usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:230:10
    at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js:253:17)
    at /usr/src/app/node_modules/xstate/lib/interpreter.js:125:23
    at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:60:13)
2021-01-07 23:55:10.514 INFO ZWAVE: Node 2 ready: Building 36 Technologies - ADC-T 2000 (Alarm.com Smart Thermostat)
```

Here are (a) the exported Node 2 configuration and (b) the `zwave-js` logs: https://gist.github.com/bachya/b2eb36f3be24878c0c78e5494f34977c

From the `zwave-js` logs, it appears that the driver receives climate mode data from the node:

```
23:55:24.843 CNTRLR   [Node 002] [~] [Thermostat Mode] mode: 1 => 1                     [Endpoint 0]
23:55:24.846 SERIAL » [ACK]                                                                   (0x06)
23:55:24.849 DRIVER « [Node 002] [REQ] [ApplicationCommand]
                      └─[ThermostatModeCCReport]
                          mode: Heat
23:55:24.855 SERIAL » 0x0109001305029840253e21                                            (11 bytes)
23:55:24.856 DRIVER » [Node 005] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      62
                      └─[SecurityCCNonceGet]
23:55:24.856 CNTRLR « [Node 002] received current thermostat mode: Heat
23:55:24.856 CNTRLR   [Node 002] [~] [Thermostat Mode] interviewComplete: tr [Endpoint 0] [internal]
```

**Comment by AlCalzone** [comment]
@robertsLando your problem :) My side seems to be working now.

**Comment by robertsLando** [comment]
>  Is it possible that the strange representation of 158°F in Home Assistant lies with z2m

`temperature_units` ? @bachya

**Comment by AlCalzone** [comment]
Guess that should be auto-detected from the device?

**Comment by robertsLando** [comment]
> Is it possible that the strange representation of 158°F in Home Assistant lies with z2m?

This could be caused by the `temperature_units` set on the climate discovered.

**Comment by robertsLando** [comment]
It's defined here: https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/Gateway.js#L1208

**Comment by bachya** [comment]
@robertsLando I'm unclear on your question. I don't think I e set units anywhere within z2m. Are you asking that my units are in Home Assistant?

**Comment by robertsLando** [comment]
> I don't think I've set units anywhere within z2m

Them are set in the discovery payload sent to hass. IMO what happens here is that the discovety payload sent them with the units `C`, but the value in in `F` and hass thinking the value that is coming is in `C` converts it to `F` giving you that

**Comment by robertsLando** [comment]
What could be wrong here is that your temperature valueId (`49-0-Air temperature`) has `C` as units instead of `F`. That's strange as the reported value in zwave logs prints `F`. To fix this you could manually edit the climate discovery payload by set `F` in the temperature units, and press store to keep the configuration persistent (otherwise an application restart would override your changes on the discovery payload). Rember that if you change the node name/location or else that changes the topics you need to remove the devices from persistence in order to make them rediscovered with the updated topics

**Comment by bachya** [comment]
Got it. I'll test this morning and get back to you.

**Comment by bachya** [comment]
Apologies for the delay; finally got around to this. Once again, started with a from-scratch installation; my details below.

After discovery completed, the `climate` device showed up in Home Assistant:

![Screen Shot 2021-01-28 at 2 06 01 PM](https://user-images.githubusercontent.com/47216/106199168-4c590300-6172-11eb-8a06-7a6014c33307.png)

Key details:

* The current temperature matches what our thermostat showed at the time: 67°F
* The target temperature (104°F) equals the `max_temp` allowed by the thermostat

I followed @robertsLando's instructions and modified the HASS Device JSON so that the `temperature_unit` was `F`. After a Home Assistant restart, the `climate` device looked like this:

![Screen Shot 2021-01-28 at 2 07 08 PM](https://user-images.githubusercontent.com/47216/106199472-bec9e300-6172-11eb-83d5-2319cab4411c.png)

Key details:

* The current temperature now shows the Celsius equivalent of the "real" thermostat temperature: (19.5°C = 67.1°F)
* The target temperature once again equals the `max_temp`, but this time, in Celsius

So, I have no clue what's going on here. 😂 

Once again, here are silly-level logs from this fresh run:

* z2m logs: https://gist.githubusercontent.com/bachya/d1264808731ebbb7538195f7a7962fae/raw/87170010ce23745514fc7352043c46d5cc1dd677/zwavejs2mqtt.log
* zwave-js logs: https://gist.githubusercontent.com/bachya/d1264808731ebbb7538195f7a7962fae/raw/87170010ce23745514fc7352043c46d5cc1dd677/zwavejs_1.log

**Comment by robertsLando** [comment]
@bachya

I have no clue :man_shrugging: What are your default scales settings in hass? C or F?

**Comment by bachya** [comment]
@robertsLando Imperial (F).

**Comment by robertsLando** [comment]
> The target temperature once again equals the max_temp, but this time, in Celsius. Once again, I'm assuming it's trying to show something larger, but can't because of max_temp.

Did you try to also change this in the discovery payload?

**Comment by bachya** [comment]
I did and after a HASS restart, that new max value does lock in.

**Comment by robertsLando** [comment]
Sorry but I have no clue about what's going on here. What I can suggest is to enable the zwavejs server from settings and give a try to the new hass zwavejs addon

**Comment by bachya** [comment]
No worries, @robertsLando. I tried the new home Assistant integration (using the websocket) and everything worked fine, so I'll go in that direction.

**Comment by robertsLando** [comment]
@bachya Perfect glad it worked and sorry for the waste of time debugging this here
