### ISSUE TITLE
Nodes constantly become dead

### ISSUE THREAD

**Issue by oleynikandrey** [zwave-js/zwavejs2mqtt#565]
Hello, I have pretty small z-wave network: z-way controller (RaZberry Controller 2016 ZWave+), 2 channel wall switch (Shenzhen Neo Electronics EU-2) and dimmer (McoHome Technology MH-P220). All devices are located in one room.

I'm constantly see error messages about timeouts, unexpected responses or nodes becoming dead.

Here is a part of the log:
```
Feb 12 15:09:24 pi npm[11047]: 15:09:24.383 CNTRLR « [Node 003] Received update for a Supervision session
Feb 12 15:09:34 pi npm[11047]: 15:09:34.341 CNTRLR   [Node 002] Timed out while waiting for a response from the node
Feb 12 15:09:35 pi npm[11047]: 15:09:35.596 CNTRLR « [Node 003] Received update for a Supervision session
Feb 12 15:09:38 pi npm[11047]: 15:09:38.180 CNTRLR « [Node 003] Received update for a Supervision session
Feb 12 15:09:39 pi npm[11047]: 15:09:39.684 CNTRLR   [Node 003] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
Feb 12 15:09:50 pi npm[11047]: 15:09:50.919 CNTRLR   [Node 003] Timed out while waiting for a response from the node
Feb 12 15:09:50 pi npm[11047]: 2021-02-12 15:09:50.921 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 71 => 85
Feb 12 15:09:52 pi npm[11047]: 2021-02-12 15:09:52.187 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:52 pi npm[11047]: 2021-02-12 15:09:52.966 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:53 pi npm[11047]: 2021-02-12 15:09:53.123 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:53 pi npm[11047]: 2021-02-12 15:09:53.304 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:56 pi npm[11047]: 15:09:56.778 CNTRLR   [Node 003] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
Feb 12 15:09:57 pi npm[11047]: 2021-02-12 15:09:57.608 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:58 pi npm[11047]: 2021-02-12 15:09:58.507 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:58 pi npm[11047]: 15:09:58.715 CNTRLR   [Node 003] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
Feb 12 15:09:58 pi npm[11047]: 2021-02-12 15:09:58.757 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:58 pi npm[11047]: 2021-02-12 15:09:58.883 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:59 pi npm[11047]: 2021-02-12 15:09:59.504 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:59 pi npm[11047]: 2021-02-12 15:09:59.532 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:59 pi npm[11047]: 2021-02-12 15:09:59.918 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:09:59 pi npm[11047]: 2021-02-12 15:09:59.966 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:10:00 pi npm[11047]: 2021-02-12 15:10:00.105 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:10:00 pi npm[11047]: 2021-02-12 15:10:00.191 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 85
Feb 12 15:10:00 pi npm[11047]: 15:10:00.265 CNTRLR   [Node 003] did not respond after 2/3 attempts. Scheduling next try in 500 ms.
Feb 12 15:10:10 pi npm[11047]: 15:10:10.813 CNTRLR   [Node 003] Timed out while waiting for a response from the node
Feb 12 15:10:11 pi npm[11047]: 2021-02-12 15:10:11.138 INFO ZWAVE: Node 3: value updated: 38-0-currentValue 85 => 99
Feb 12 15:10:12 pi npm[11047]: 15:10:12.210 CNTRLR « [Node 003] Received update for a Supervision session
Feb 12 15:10:15 pi npm[11047]: 15:10:15.240 CNTRLR   [Node 002] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
Feb 12 15:10:19 pi npm[11047]: 15:10:19.999 CNTRLR   [Node 002] did not respond after 2/3 attempts. Scheduling next try in 500 ms.
Feb 12 15:10:24 pi npm[11047]: 15:10:24.792 CNTRLR   [Node 002] Node 2 did not respond after 3 attempts, it is presumed dead
Feb 12 15:10:24 pi npm[11047]: 2021-02-12 15:10:24.804 INFO ZWAVE: Node 2 is now dead
Feb 12 15:10:24 pi npm[11047]: 15:10:24.805 CNTRLR   [Node 002] The node is now dead.
Feb 12 15:10:33 pi npm[11047]: 2021-02-12 15:10:33.954 ERROR ZWAVE-SERVER: Unexpected error Failed to send the command after 3 attempts (Status NoAck)
Feb 12 15:10:33 pi npm[11047]: ZWaveError: Failed to send the command after 3 attempts (Status NoAck)
Feb 12 15:10:33 pi npm[11047]:     at Object.sendDataErrorToZWaveError (/opt/zwavejs2mqtt/node_modules/zwave-js/src/lib/driver/StateMachineShared.ts:112:12)
Feb 12 15:10:33 pi npm[11047]:     at /opt/zwavejs2mqtt/node_modules/zwave-js/src/lib/driver/SendThreadMachine.ts:437:4
Feb 12 15:10:33 pi npm[11047]:     at /opt/zwavejs2mqtt/node_modules/xstate/lib/utils.js:410:33
Feb 12 15:10:33 pi npm[11047]:     at Array.reduce (<anonymous>)
Feb 12 15:10:33 pi npm[11047]:     at Object.updateContext (/opt/zwavejs2mqtt/node_modules/xstate/lib/utils.js:400:25)
Feb 12 15:10:33 pi npm[11047]:     at Object.resolveActions (/opt/zwavejs2mqtt/node_modules/xstate/lib/actions.js:409:19)
Feb 12 15:10:33 pi npm[11047]:     at StateNode.resolveTransition (/opt/zwavejs2mqtt/node_modules/xstate/lib/StateNode.js:787:35)
Feb 12 15:10:33 pi npm[11047]:     at StateNode.transition (/opt/zwavejs2mqtt/node_modules/xstate/lib/StateNode.js:733:21)
Feb 12 15:10:33 pi npm[11047]:     at StateNode.resolveRaisedTransition (/opt/zwavejs2mqtt/node_modules/xstate/lib/StateNode.js:738:22)
Feb 12 15:10:33 pi npm[11047]:     at StateNode.resolveTransition (/opt/zwavejs2mqtt/node_modules/xstate/lib/StateNode.js:873:39)
Feb 12 15:10:33 pi npm[11047]:     at StateNode.transition (/opt/zwavejs2mqtt/node_modules/xstate/lib/StateNode.js:733:21)
Feb 12 15:10:33 pi npm[11047]:     at /opt/zwavejs2mqtt/node_modules/xstate/lib/interpreter.js:602:34
Feb 12 15:10:33 pi npm[11047]:     at Object.provide (/opt/zwavejs2mqtt/node_modules/xstate/lib/serviceScope.js:11:18)
Feb 12 15:10:33 pi npm[11047]:     at Interpreter.nextState (/opt/zwavejs2mqtt/node_modules/xstate/lib/interpreter.js:601:38)
Feb 12 15:10:33 pi npm[11047]:     at /opt/zwavejs2mqtt/node_modules/xstate/lib/interpreter.js:124:39
Feb 12 15:10:33 pi npm[11047]:     at Scheduler.process (/opt/zwavejs2mqtt/node_modules/xstate/lib/scheduler.js:60:13)
Feb 12 15:10:33 pi npm[11047]: 15:10:33.964 DRIVER   unexpected response, discarding...
Feb 12 15:10:33 pi npm[11047]: 15:10:33.966 DRIVER   unexpected response, discarding...
Feb 12 15:10:33 pi npm[11047]: 15:10:33.968 DRIVER   unexpected response, discarding...
Feb 12 15:10:33 pi npm[11047]: 15:10:33.972 DRIVER     no handlers registered!
Feb 12 15:10:33 pi npm[11047]: 15:10:33.974 DRIVER     no handlers registered!
Feb 12 15:10:33 pi npm[11047]: 15:10:33.977 DRIVER     no handlers registered!
Feb 12 15:10:33 pi npm[11047]: 15:10:33.985 CNTRLR » [Node 002] pinging the node...
Feb 12 15:10:44 pi npm[11047]: 15:10:44.117 CNTRLR   [Node 003] Timed out while waiting for a response from the node
Feb 12 15:10:48 pi npm[11047]: 15:10:48.371 CNTRLR   [Node 002] Node 2 did not respond after 1 attempts, it is presumed dead
Feb 12 15:10:48 pi npm[11047]: 15:10:48.397 CNTRLR   [Node 002] ping failed: Failed to send the command after 1 attempts (Status No
Feb 12 15:10:48 pi npm[11047]:                       Ack)
Feb 12 15:10:48 pi npm[11047]: 2021-02-12 15:10:48.400 ERROR ZWAVE-SERVER: Unexpected error The message cannot be sent because node 2 is dead
```

Could someone help me to find a reason for such behaviour?

**Comment by robertsLando** [comment]
cc @AlCalzone
