### ISSUE TITLE
[bug] The new json-logic-js dependency from node-zwave-js isn't being picked up in a custom docker image

### ISSUE THREAD

**Issue by rccoleman** [zwave-js/zwavejs2mqtt#669]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [x] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build )

Manually built docker image as per instructions at https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/docker_custom_builds

zwavejs2mqtt version: 1.2.2
zwavejs version: 6.4.0

### Describe the bug

Pulling the latest "master" branch of node-zwave-js and zwavejs2mqtt and building based on the instructions at https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/docker_custom_builds yields a container that constantly restarts with the following error in the docker logs:

```
Error: Cannot find module 'json-logic-js'
Require stack:
- /usr/src/app/node_modules/@zwave-js/config/build/Logic.js
- /usr/src/app/node_modules/@zwave-js/config/build/Devices.js
- /usr/src/app/node_modules/@zwave-js/config/build/ConfigManager.js
- /usr/src/app/node_modules/@zwave-js/config/build/index.js
- /usr/src/app/node_modules/zwave-js/build/lib/commandclass/MultilevelSensorCC.js
- /usr/src/app/node_modules/zwave-js/build/lib/commandclass/index.js
- /usr/src/app/node_modules/zwave-js/CommandClass.js
- /usr/src/app/node_modules/zwave-js/index.js
- /usr/src/app/lib/ZwaveClient.js
- /usr/src/app/node_modules/app-root-path/lib/app-root-path.js
- /usr/src/app/node_modules/app-root-path/index.js
- /usr/src/app/bin/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@zwave-js/config/src/Logic.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/@zwave-js/config/build/Logic.js',
    '/usr/src/app/node_modules/@zwave-js/config/build/Devices.js',
    '/usr/src/app/node_modules/@zwave-js/config/build/ConfigManager.js',
    '/usr/src/app/node_modules/@zwave-js/config/build/index.js',
    '/usr/src/app/node_modules/zwave-js/build/lib/commandclass/MultilevelSensorCC.js',
    '/usr/src/app/node_modules/zwave-js/build/lib/commandclass/index.js',
    '/usr/src/app/node_modules/zwave-js/CommandClass.js',
    '/usr/src/app/node_modules/zwave-js/index.js',
    '/usr/src/app/lib/ZwaveClient.js',
    '/usr/src/app/node_modules/app-root-path/lib/app-root-path.js',
    '/usr/src/app/node_modules/app-root-path/index.js',
    '/usr/src/app/bin/www'
  ]
}
```
I suspect that this is related to the recent addition of conditional logic in the JSON config files, but I can't figure out what's missing.

### To Reproduce

Build a custom container based on the master branches and the instructions above and attempt to deploy it.

### Expected behavior

The container should start and run properly.

### Additional context

The dependabot also broke Dockerfile.contrib again by trying to move it to Alpine from Debian Buster.  This was the fix for the last time this happend: https://github.com/zwave-js/zwavejs2mqtt/commit/b048fcbb6885456e0f73e7aa22995a5fba71eba7#diff-4ddc2e10398d5c169795b7937f893ec72d2619b395259c592156a5dd0b476c9f

**Comment by scyto** [comment]
this fixed the alpine issue, but not the other issues https://github.com/zwave-js/zwavejs2mqtt/pull/666

**Comment by AlCalzone** [comment]
Does this also happen if you run `yarn install` after pulling the latest changes from Github?

**Comment by rccoleman** [comment]
Yes, it does.

**Comment by robertsLando** [comment]
@AlCalzone ?

**Comment by AlCalzone** [comment]
I'm honestly confused here. json-logic-js is a dependency of `@zwave-js/config`, there is no package-lock.json that says otherwise and `json-logic-js` is included in `yarn.lock`.

**Comment by rccoleman** [comment]
Are either of you able to repro it?  It was just a matter of following the instructions for generating the container build, with the slight complication that dependabot keeps breaking Dockerfile.contrib and needs to be manually fixed. I'll run through a clean install later today and capture the results.

**Comment by AlCalzone** [comment]
Yeah, I can reproduce

**Comment by rccoleman** [comment]
That's good, I guess.  I'm now getting a new error when I create a test dir and clone master of both repos from scratch:

```
#14 27.04 [3/4] Linking dependencies...
#14 27.05 warning " > @xstate/test@0.4.1" has unmet peer dependency "xstate@^4.9.0".
#14 27.05 warning "@xstate/test > @xstate/graph@1.3.0" has unmet peer dependency "xstate@^4.9.0".
#14 27.06 warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.2" has unmet peer dependency "@octokit/core@>=3".
#14 39.11 [4/4] Building fresh packages...
#14 39.73 error /home/node/node-zwave-js/node_modules/node-expat: Command failed.
#14 39.73 Exit code: 1
#14 39.73 Command: node-gyp rebuild
#14 39.73 Arguments:
#14 39.73 Directory: /home/node/node-zwave-js/node_modules/node-expat
#14 39.73 Output:
#14 39.73 gyp info it worked if it ends with ok
#14 39.73 gyp info using node-gyp@5.1.1
#14 39.73 gyp info using node@12.20.2 | linux | x64
#14 39.73 gyp ERR! find Python
#14 39.73 gyp ERR! find Python Python is not set from command line or npm configuration
#14 39.73 gyp ERR! find Python Python is not set from environment variable PYTHON
#14 39.73 gyp ERR! find Python checking if "python" can be used
#14 39.73 gyp ERR! find Python - "python" is not in PATH or produced an error
#14 39.73 gyp ERR! find Python checking if "python2" can be used
#14 39.73 gyp ERR! find Python - "python2" is not in PATH or produced an error
#14 39.73 gyp ERR! find Python checking if "python3" can be used
#14 39.73 gyp ERR! find Python - "python3" is not in PATH or produced an error
#14 39.73 gyp ERR! find Python
#14 39.73 gyp ERR! find Python **********************************************************
#14 39.73 gyp ERR! find Python You need to install the latest version of Python.
#14 39.73 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#14 39.73 gyp ERR! find Python you can try one of the following options:
#14 39.73 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#14 39.73 gyp ERR! find Python   (accepted by both node-gyp and npm)
#14 39.73 gyp ERR! find Python - Set the environment variable PYTHON
#14 39.73 gyp ERR! find Python - Set the npm configuration variable python:
#14 39.73 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#14 39.73 gyp ERR! find Python For more information consult the documentation at:
#14 39.73 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#14 39.73 gyp ERR! find Python **********************************************************
#14 39.73 gyp ERR! find Python
#14 39.73 gyp ERR! configure error
#14 39.73 gyp ERR! stack Error: Could not find any Python installation to use
#14 39.73 gyp ERR! stack     at PythonFinder.fail (/home/node/node-zwave-js/node_modules/node-gyp/lib/find-python.js:307:47)
#14 39.73 gyp ERR! stack     at PythonFinder.runChecks (/home/node/node-zwave-js/node_modules/node-gyp/lib/find-python.js:136:21)
#14 39.73 gyp ERR! stack     at PythonFinder.<anonymous> (/home/node/node-zwave-js/node_modules/node-gyp/lib/find-python.js:179:16)
#14 39.73 gyp ERR! stack     at PythonFinder.execFileCallback (/home/node/node-zwave-js/node_modules/node-gyp/lib/find-python.js:271:16)
#14 39.73 gyp ERR! stack     at exithandler (child_process.js:315:5)
#14 39.73 gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
#14 39.73 gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
#14 39.73 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
#14 39.73 gyp ERR! stack     at onErrorNT (internal/child_process.js:470:16)
#14 39.73 gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
#14 39.73 gyp ERR! System Linux 5.4.0-65-generic
#14 39.73 gyp ERR! command "/usr/local/bin/node" "/home/node/node-zwave-js/node_modules/.bin/node-gyp" "rebuild"
#14 39.73 gyp ERR! cwd /home/node/node-zwave-js/node_modules/node-expat
#14 39.73 gyp ERR! node -v v12.20.2
#14 39.73 gyp ERR! node-gyp -v v5.1.1
#14 39.73 gyp ERR! not ok
#14 39.73 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install --network-timeout=${YARN_NETWORK_TIMEOUT}]: exit code: 1

```

Looks like that showed up with the move from erbium-buster to erbium-buster-slim originally from here: https://github.com/zwave-js/zwavejs2mqtt/commit/f4ff24add9721e81f4cf401d304ddfbbf75f4c65.  I switched back and at least the container build succeeds.

**Comment by scyto** [comment]
i built a repro this morning, image is at scyto/zwavejs2mqtt:patch-2 if anyone wants it.

**Comment by AlCalzone** [comment]
I have two theories why this is happening:

a) The problem has to do with the version magic the dockerfile does. This is the end of the `npm ls` command inside the container @scyto built:

```
`-- UNMET PEER DEPENDENCY zwave-js@6.4.0-b358ce7 invalid
  +-- @alcalzone/jsonl-db@1.2.4 extraneous
  +-- @sentry/integrations@5.30.0 extraneous
  +-- @sentry/node@5.30.0 extraneous
  +-- UNMET DEPENDENCY @zwave-js/config@^6.4.0
  +-- UNMET DEPENDENCY @zwave-js/core@^6.4.0
  +-- UNMET DEPENDENCY @zwave-js/serial@^6.4.0
  +-- UNMET DEPENDENCY @zwave-js/shared@^6.2.0
  +-- alcalzone-shared@3.0.2 extraneous
  +-- ansi-colors@4.1.1
  +-- fs-extra@9.0.1 extraneous
  +-- reflect-metadata@0.1.13 extraneous
  +-- serialport@9.0.7 deduped
  +-- source-map-support@0.5.19
  | +-- buffer-from@1.1.1
  | `-- source-map@0.6.1 deduped
  +-- winston@3.3.3 deduped
  `-- xstate@4.16.2 extraneous

npm ERR! peer dep missing: zwave-js@^6.4, required by @zwave-js/server@1.0.0-beta.8
npm ERR! extraneous: @zwave-js/config@6.4.0-b358ce7 /usr/src/app/node_modules/@zwave-js/config
npm ERR! extraneous: @zwave-js/core@6.4.0-b358ce7 /usr/src/app/node_modules/@zwave-js/core
npm ERR! extraneous: @zwave-js/serial@6.4.0-b358ce7 /usr/src/app/node_modules/@zwave-js/serial
npm ERR! extraneous: @zwave-js/shared@6.2.0-b358ce7 /usr/src/app/node_modules/@zwave-js/shared
```
According to this theory, the local version has been changed to the prerelease version `zwave-js@6.4.0-b358ce7`, but zwavejs2mqtt or the server wants `zwave-js@^6.4`, which `zwave-js@6.4.0-b358ce7` does **not** satisfy.

---

b) `zwave-js` is a peer dependency. Not sure what this implies but it could be a problem.

I'm investigating a) now.

**Comment by rccoleman** [comment]
(a) looks like it may be an artifact of the custom build.  All version numbers get (I think) the commit number added to them, and that shows up in the UI.

**Comment by AlCalzone** [comment]
I've removed the version magic and it still fails.

**Comment by scyto** [comment]
i just tried it figure out how to build from master and master into my own container
this isn't pretty or small or elegant- that wasn't the goal (and i haven't attempted multistage builds before)
it seems to work - no errors on start
however i am unclear how to tell if it really is master/master of each branch; if i shell in is there a way?
i also have no idea what about this is different other than i used the instructions of the io doc pages.

```
# Use alpine base image
FROM node:15.9.0-alpine
# ARG YARN_NETWORK_TIMEOUT=300000

# build zwavejs
RUN apk update \
  && apk add --no-cache git python3  linux-headers yarn coreutils alpine-sdk \
  && git clone --depth 1 --branch master https://github.com/zwave-js/node-zwave-js.git \
  && git clone --depth 1 --branch master https://github.com/zwave-js/zwavejs2mqtt.git

RUN npm install --g lerna \
  && cd node-zwave-js \
  && yarn \
  && yarn run build \
  && lerna exec -- yarn link \
  && cd ..

# build zwavejs2mqtt
RUN cd zwavejs2mqtt \
  && npm install \
  && npm run build 

RUN  yarn link zwave-js @zwave-js/core @zwave-js/config @zwave-js/serial @zwave-js/shared

# Define environment variable
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV LANG C.UTF-8
ENV TZ America/Los_Angeles
WORKDIR /zwavejs2mqtt

# Run  when the container launches
CMD ["node", "bin/www"]

**Comment by scyto** [comment]
are these still failing for you?
my github actions build using dockerfile.contrib just worked and gave me a working build with

App Version 1.3.0+fec72b7.fec72b7
Zwavejs Version 6.5.0-e0b52b1
Zwavejs-server Version 1.0.0-beta.9

**Comment by rccoleman** [comment]
I'm getting the same python error with the latest pull from both repos that I posted [here](https://github.com/zwave-js/zwavejs2mqtt/issues/669#issuecomment-783604273).  I was able to fix it before by not using the `-slim` image.
