### ISSUE TITLE
[bug] All devices but 2 are missing in HA since updating to 1.4.0

### ISSUE THREAD

**Issue by syphernl** [zwave-js/zwavejs2mqtt#734]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [X] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.4.0
zwavejs version: 6.4.0

### Describe the bug

After updating from `1.3.0` to `1.4.0` my devices have a Manufacturer and Product name (which was broken since 1.2.0) but now the devices are missing from HA. 
If I remove the integration and add it again, it detects 2 devices (the Z-Wave stick and a powered Fibaro Plug). 

All other devices (a bunch of powered/hardwired devices like plugs and switches) and battery devices are all missing. 
When I downgrade to 1.3.0 again these immediately show up when I add the integration to HA, albeit with no names/details except for node id's.

### To Reproduce

See above

### Expected behavior

Manufacturer / product names filled in, all devices in ZW2MQTT available in HA.

### Additional context
The issue with Manufacturer/Product names: #673

**Comment by robertsLando** [comment]
@syphernl Please attach logs

**Comment by robertsLando** [comment]
AFAIK there is a patch needed on hass integration in order to make it working with latest zwavejs version so please wait

**Comment by syphernl** [comment]
> AFAIK there is a patch needed on hass integration in order to make it working with latest zwavejs version so please wait

That probably explains this HASS log entry..
```text
2021-02-24 17:57:08 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Z-Wave JS for zwave_js
Traceback (most recent call last):
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/config_entries.py", line 325, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/zwave_js/__init__.py", line 319, in async_unload_entry
    await disconnect_client(
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/zwave_js/__init__.py", line 293, in disconnect_client
    await asyncio.gather(listen_task, platform_task)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/zwave_js/__init__.py", line 241, in start_platforms
    async_on_node_added(node)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/zwave_js/__init__.py", line 116, in async_on_node_added
    async_on_node_ready(node)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/zwave_js/__init__.py", line 95, in async_on_node_ready
    for disc_info in async_discover_values(node):
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/components/zwave_js/discovery.py", line 257, in async_discover_values
    and value.node.device_class.generic not in schema.device_class_generic
TypeError: unhashable type: 'dict' 
```
