### ISSUE TITLE
[bug] zwave-js fatal error on replace failed node

### ISSUE THREAD

**Issue by bs42** [zwave-js/zwavejs2mqtt#808]
### Version

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 2.1.0
zwavejs version: 6.6.0

### Describe the bug

2021-03-03 18:12:45.564 INFO ZWAVE: Calling api replaceFailedNode with args: [ 6, false, [length]: 2 ]                       
2021-03-03 18:12:50.116 INFO ZWAVE: Controller status: Non-secure inclusion started                                          
2021-03-03 18:12:50.120 INFO ZWAVE: Success zwave api call replaceFailedNode { success: true, message: 'Success zwave api call
', result: true }                                                                                                            
2021-03-03 18:12:59.943 INFO ZWAVE: Controller status: Inclusion stopped                                                     
2021-03-03 18:12:59.966 INFO ZWAVE: Node 6: removed                                                                          
2021-03-03 18:12:59.966 INFO ZWAVE: Node removed 6                                                                            
2021-03-03 18:13:28.476 INFO ZWAVE: Node 6: added                                                                            
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which wa
s not handled with .catch(). The promise rejected with the reason:                                                           
TypeError: Cannot read property 'basic' of undefined                                                                         
    at Object.dumpDeviceClass (/usr/src/app/node_modules/@zwave-js/server/dist/lib/state.js:85:26)                           
    at Object.dumpNode (/usr/src/app/node_modules/@zwave-js/server/dist/lib/state.js:42:67)                                  
    at /usr/src/app/node_modules/@zwave-js/server/dist/lib/forward.js:23:31                                                  
    at Array.forEach (<anonymous>)                                                                                           
    at ZWaveController.<anonymous> (/usr/src/app/node_modules/@zwave-js/server/dist/lib/forward.js:20:34)                    
    at ZWaveController.emit (node:events:390:22)                                                                             
    at ZWaveController.EventEmitter.emit (node:domain:470:12)                                                                
    at ZWaveController.handleReplaceNodeRequest (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:1203:11)
    at Driver.handleRequest (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1936:22)                            
    at Driver.handleUnsolicitedMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1670:5)                  

### To Reproduce

Attempt to replace a dead node.

**Comment by robertsLando** [comment]
Oh that's from zwavejs server
