### ISSUE TITLE
Keeps Crashing.. :(

### ISSUE THREAD

**Issue by WebhandsNL** [zwave-js/zwavejs2mqtt#904]
Hi Guys,

Trying to get it working but unfortunately it doest for me..

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'type' of undefined
    at Object.dumpMetadata (/zwavejs2mqtt/node_modules/@zwave-js/server/dist/lib/state.js:42:24)
    at /zwavejs2mqtt/node_modules/@zwave-js/server/dist/lib/forward.js:91:58
    at Array.forEach (<anonymous>)
    at notifyNodeOnValueOrMetadataUpdates (/zwavejs2mqtt/node_modules/@zwave-js/server/dist/lib/forward.js:86:34)
    at ZWaveNode.<anonymous> (/zwavejs2mqtt/node_modules/@zwave-js/server/dist/lib/forward.js:147:21)
    at ZWaveNode.emit (node:events:390:22)
    at ZWaveNode.EventEmitter.emit (node:domain:470:12)
    at ZWaveNode.translateValueEvent (/zwavejs2mqtt/node_modules/zwave-js/src/lib/node/Node.ts:346:8)
    at ValueDB.emit (node:events:378:20)
    at ValueDB.EventEmitter.emit (node:domain:470:12)

// Edit

It happends with Fibaro Motion Sensors.. working with an Aeotec Gen5+ usb stick.
Resetted it to factory settings, removed all nodes and tried adding them again didn't work either.

**Comment by robertsLando** [comment]
This is a problem on hass zwavejs server side. Should be fixed on next release
