### ISSUE TITLE
[bug] docker run fails on raspberry pi

### ISSUE THREAD

**Issue by sieukrem** [zwave-js/zwavejs2mqtt#95]
**Version**

Build/Run method
- [x] Docker (Digest  sha256:3b37d20d1f5b2e508ee8a261101b22d825ced779a6ca772719452a6c9f0e21ae)

zwavejs2mqtt version:  1.0.0-alpha.1

**Describe the bug**
I start the fresh loaded docker image zwavejs/zwavejs2mqtt with folder mount, where no files currently exist.

I see following output.

```

 ______                       _     ___                  _   _
|___  /                      (_)   |__ \                | | | |
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |
                           |__/                       |_|

2020-12-20 13:30:33.412 WARN STORE: settings.json not found
2020-12-20 13:30:33.620 WARN STORE: scenes.json not found
2020-12-20 13:30:33.625 WARN STORE: nodes.json not found
/bin/sh: git: not found
2020-12-20 13:30:38.942 INFO APP: Version: 1.0.0-alpha.1
2020-12-20 13:30:38.945 INFO APP: Application path:/usr/src/app
TypeError: Cannot read property 'logEnabled' of undefined
    at setupLogging (/usr/src/app/app.js:43:31)
    at startGateway (/usr/src/app/app.js:56:3)
    at start (/usr/src/app/app.js:38:3)
    at /usr/src/app/bin/www:98:5
    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/src/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

```

**Expected behavior**
* Zwave2mqtt starts without any errors and does not crash at the end.
* I don't expect dependency to `git` inside of docker container

**Additional context**
I try to run on raspberry pi which was able to run ozw variant of zwave2mqtt

**Comment by sieukrem** [comment]
@ahochsteger I assume the error I am observing relies on changes from #67. Is there  a workaround for missing settings?

**Comment by ahochsteger** [comment]
@sieukrem thanks for reporting - yes this bug has been introduced with #67.

A simple workaround is to create the file `store/settings.json` with at least the following contents:
```json
{"gateway":{}}
```

A bugfix will be available shortly.
