### ISSUE TITLE
[bug] volume doesn't allow entry for sound switch device

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#960]
### Version

**Checklist:**

- [ X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is **not** described there.
- [ ] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt: 3.0.2+4a6a5c5.4a6a5c5
zwave-js: 7.0.1-199b92c
(Built off both current masters)

### Describe the bug

The Zooz ZSE19 is a sound switch capable multi-siren. The device reports and we setup a volume field, but it is presented as a drop-down and you cannot enter an actual value. Its presented as if allowManualEntry was false.

![Screen Shot 2021-03-27 at 9 33 06 PM](https://user-images.githubusercontent.com/33612110/112739656-0d61e680-8f44-11eb-9630-99d108db5ce8.png)

![Screen Shot 2021-03-27 at 9 33 12 PM](https://user-images.githubusercontent.com/33612110/112739659-10f56d80-8f44-11eb-965d-1915593cddbb.png)

Additionally, trying to set the one value displayed (0) results in the following error at the top of the UI:

![Screen Shot 2021-03-27 at 9 30 19 PM](https://user-images.githubusercontent.com/33612110/112739642-fb804380-8f43-11eb-830e-5aaa32010dd5.png)

### Additional context

zwavejs2mqtt log:

```
2021-03-27 21:42:20.874 DEBUG SOCKET: Event ZWAVE_API emitted to X0nrlKre0JFsDayiAAAa
2021-03-27 21:42:20.877 INFO ZWAVE: Calling api writeValue with args: [
  { nodeId: 148, commandClass: 121, endpoint: 0, property: 'volume' },
  0,
  [length]: 2
]
2021-03-27 21:42:20.892 DEBUG MQTT: Publishing to homeassistant/_EVENTS/ZWAVE_GATEWAY-MQTT/driver/driver_error: {
  data: [
    ZWaveError: Sound Switch: "volume" is not a supported property
        at Object.throwUnsupportedProperty (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/API.ts:38:8)
        at Proxy.SoundSwitchCCAPI.<computed> (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/SoundSwitchCC.ts:270:4)
        at ZWaveNode.setValue (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:699:14)
        at ZwaveClient.writeValue (/usr/src/app/lib/ZwaveClient.js:2656:53)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at ZwaveClient.callApi (/usr/src/app/lib/ZwaveClient.js:2507:18)
        at SocketManager.<anonymous> (/usr/src/app/app.js:380:22) {
      [stack]: 'ZWaveError: Sound Switch: "volume" is not a supported property\n' +
        '    at Object.throwUnsupportedProperty (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/API.ts:38:8)\n' +
        '    at Proxy.SoundSwitchCCAPI.<computed> (/usr/src/app/node_modules/zwave-js/src/lib/commandclass/SoundSwitchCC.ts:270:4)\n' +
        '    at ZWaveNode.setValue (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:699:14)\n' +
        '    at ZwaveClient.writeValue (/usr/src/app/lib/ZwaveClient.js:2656:53)\n' +
        '    at runMicrotasks (<anonymous>)\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
        '    at ZwaveClient.callApi (/usr/src/app/lib/ZwaveClient.js:2507:18)\n' +
        '    at SocketManager.<anonymous> (/usr/src/app/app.js:380:22)',
      [message]: 'Sound Switch: "volume" is not a supported property',
      code: 36,
      context: undefined,
      transactionSource: undefined,
      name: 'ZWaveError'
    },
    [length]: 1
  ]
} with options { qos: 1, retain: false }
2021-03-27 21:42:20.878 INFO ZWAVE: Writing 0 to 148-121-0-volume
2021-03-27 21:42:20.882 INFO ZWAVE: Controller status: Driver: Sound Switch: "volume" is not a supported property
2021-03-27 21:42:20.894 ERROR ZWAVE: Unable to write 0 on 148-121-0-volume
2021-03-27 21:42:20.895 INFO ZWAVE: Success zwave api call writeValue { success: true, message: 'Success zwave api call', result: undefined }
```

(Nothing appears in the zwavejs_1.log file for zwave, so nothing is sent to the device.)

[node_148.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6216704/node_148.json.zip)

[node 148 interview.log](https://github.com/zwave-js/zwavejs2mqtt/files/6216713/node.148.interview.log)

**Comment by robertsLando** [comment]
That's weird, @AlCalzone I think that should not be there, maybe a regression?

**Comment by AlCalzone** [comment]
It has always been that way. Either changing that value should just update the value in the DB without doing anything else - or we should make it readonly.

The problem is that `volume` alone is not enough and as such it isn't really a good fit for the `setValue` API. Playing a tone requires the tone ID and optionally the volume.
Probably the ideal solution would be https://github.com/zwave-js/node-zwave-js/issues/1321 and treating the volume as a "meta" value for the toneId

**Comment by blhoward2** [comment]
There are other boxes for tone and default volume.
